/**
 * 홍보 전단지 여덟 장.
 *
 * 전단지는 «손에 쥐고 삼 초» 짜리 인쇄물입니다. 그래서 여덟 장 모두
 * 같은 규칙을 지킵니다 — 위에서 아래로 큰 글자 하나, 그 아래 설명 한 덩이,
 * 맨 아래 연락처. 삼 초 안에 «무엇을 파는 곳인가» 가 읽히지 않으면 그
 * 전단지는 실패한 것이라, 제목과 본문의 크기 차이를 세 배 이상 벌렸습니다.
 *
 * 양면은 둘입니다(카페 오픈·필라테스). 뒷면은 앞면에서 못 다 한 목록을
 * 받는 자리로 쓰고, 앞면에는 절대 목록을 넣지 않았습니다.
 */

import {
  INK,
  bullets,
  composeAll,
  ellipse,
  image,
  priceRow,
  rect,
  rule,
  text,
  artBackground,
  type Draft,
} from "@/lib/print/templates/kit";

const DRAFTS: Draft[] = [
  /* ---------------------------------------------------------
     1. 카페 오픈 — 사진 한 장으로 시작하고 뒷면에 차림표
     --------------------------------------------------------- */
  {
    id: "flyer-cafe-open",
    name: "로스터리 오픈",
    note: "사진 한 장을 위에 크게. 뒷면은 차림표로 받습니다.",
    industry: "cafe",
    style: "photo",
    palette: ["warm", "ink"],
    art: ["flyer-cafe-photo"],
    tags: ["오픈", "카페", "양면"],
    background: { color: "#ffffff" },
    backgroundBack: { color: INK.cream },
    build: ({ w, bleed }) => [
      image("flyer-cafe-photo", { x: -bleed, y: -bleed, w: w + bleed * 2, h: 168 + bleed, focusY: 0.62 }),

      text({
        x: 16,
        y: 184,
        w: 100,
        h: 5,
        text: "NEW OPEN · 성산동",
        size: 9.5,
        weight: 700,
        color: INK.amber,
        letterSpacing: 0.24,
        font: "gothic-a1",
      }),
      text({
        x: 16,
        y: 196,
        w: w - 32,
        h: 34,
        text: "매일 아침 여섯 시,\n원두를 볶습니다",
        size: 27,
        weight: 700,
        color: INK.black,
        lineHeight: 1.32,
        letterSpacing: -0.02,
        font: "gothic-a1",
      }),
      text({
        x: 16,
        y: 236,
        w: 118,
        h: 14,
        text: "골목 안쪽 열두 평 로스터리입니다. 그날 볶은 원두로만 내리고,\n남으면 다음 날 팔지 않습니다.",
        size: 10.5,
        color: INK.soft,
        lineHeight: 1.75,
      }),

      rule({ x: 16, y: 258, w: w - 32 }),

      text({
        x: 16,
        y: 266,
        w: 60,
        h: 12,
        text: "평일 08:00 – 21:00\n주말 10:00 – 20:00\n월요일 휴무",
        size: 9.5,
        color: INK.black,
        lineHeight: 1.8,
      }),
      text({
        x: 86,
        y: 266,
        w: 62,
        h: 12,
        text: "서울 마포구 성미산로 12\n02-336-0000\n@cardly.roasters",
        size: 9.5,
        color: INK.grey,
        lineHeight: 1.8,
      }),
      rect({ x: 152, y: 262, w: 42, h: 20, fill: INK.amber, radius: 3 }),
      text({
        x: 152,
        y: 268,
        w: 42,
        h: 8,
        text: "첫 주 아메리카노\n2,000원",
        size: 8.5,
        weight: 700,
        color: "#ffffff",
        align: "center",
        lineHeight: 1.5,
      }),

      /* ── 뒷면 ── */
      text({
        side: "back",
        x: 16,
        y: 26,
        w: w - 32,
        h: 12,
        text: "MENU",
        size: 10,
        weight: 700,
        color: INK.amber,
        letterSpacing: 0.4,
        align: "center",
        font: "gothic-a1",
      }),
      text({
        side: "back",
        x: 16,
        y: 40,
        w: w - 32,
        h: 12,
        text: "카들리 로스터스",
        size: 20,
        weight: 700,
        color: INK.black,
        align: "center",
        font: "gothic-a1",
      }),
      rule({ side: "back", x: 40, y: 64, w: w - 80, fill: INK.sand, h: 0.6 }),

      ...[
        ["아메리카노", "그날의 원두, 뜨겁게 또는 차갑게", "4,500"],
        ["카페 라테", "국산 우유", "5,000"],
        ["핸드드립", "산지 한 가지를 골라 드립니다", "6,500"],
        ["콜드브루", "열여덟 시간 내린 것", "5,500"],
        ["바닐라 라테", "직접 만든 시럽", "5,800"],
        ["플레인 스콘", "버터를 아끼지 않았습니다", "3,800"],
      ].flatMap(([name, desc, price], i) =>
        priceRow({
          x: 30,
          y: 80 + i * 26,
          w: w - 60,
          name,
          desc,
          price,
          nameSize: 12.5,
          descSize: 9,
          side: "back",
        }),
      ),

      rule({ side: "back", x: 40, y: 246, w: w - 80, fill: INK.sand, h: 0.6 }),
      text({
        side: "back",
        x: 16,
        y: 256,
        w: w - 32,
        h: 12,
        text: "서울 마포구 성미산로 12 · 02-336-0000\n합정역 5번 출구에서 걸어서 7분",
        size: 9.5,
        color: INK.grey,
        align: "center",
        lineHeight: 1.8,
      }),
    ],
  },

  /* ---------------------------------------------------------
     2. 학원 봄학기 모집 — 색면 위에 제목
     --------------------------------------------------------- */
  {
    id: "flyer-academy-spring",
    name: "봄학기 모집",
    note: "위쪽 색면이 제목을 받치고, 아래는 반과 시간표.",
    industry: "academy",
    style: "flat",
    palette: ["navy", "warm"],
    art: ["flyer-academy-flat"],
    tags: ["학원", "모집", "시간표"],
    background: { color: "#ffffff" },
    build: ({ w, bleed }) => [
      rect({ x: -bleed, y: -bleed, w: w + bleed * 2, h: 128 + bleed, fill: INK.navy }),
      image("flyer-academy-flat", {
        x: -bleed,
        y: 62,
        w: w + bleed * 2,
        h: 66,
        opacity: 0.9,
      }),

      text({
        x: 16,
        y: 24,
        w: w - 32,
        h: 5,
        text: "2026 봄학기 · 3월 2일 개강",
        size: 10,
        weight: 700,
        color: "#a9c0e8",
        letterSpacing: 0.14,
      }),
      text({
        x: 16,
        y: 36,
        w: w - 40,
        h: 22,
        text: "한 반 여덟 명,\n선생님이 이름을 압니다",
        size: 22,
        weight: 700,
        color: "#ffffff",
        lineHeight: 1.36,
        letterSpacing: -0.02,
        font: "gothic-a1",
      }),

      text({
        x: 16,
        y: 146,
        w: 96,
        h: 16,
        text: "초등 3학년부터 중등 3학년까지, 국어·영어·수학 세 과목을 엽니다.\n숙제는 학원에서 끝내고 갑니다.",
        size: 10.5,
        color: INK.soft,
        lineHeight: 1.8,
      }),

      rule({ x: 16, y: 182, w: w - 32, fill: INK.line }),

      ...[
        ["국어", "월·수·금 16:00", "초3–중3"],
        ["영어", "화·목 17:00", "초4–중3"],
        ["수학", "월–금 19:00", "중1–중3"],
      ].flatMap(([subject, when, who], i) => [
        text({
          x: 16,
          y: 192 + i * 20,
          w: 30,
          h: 6,
          text: subject,
          size: 13,
          weight: 700,
          color: INK.navy,
          font: "gothic-a1",
        }),
        text({
          x: 50,
          y: 193 + i * 20,
          w: 70,
          h: 6,
          text: when,
          size: 11,
          color: INK.black,
        }),
        text({
          x: 130,
          y: 193 + i * 20,
          w: 64,
          h: 6,
          text: who,
          size: 10.5,
          color: INK.grey,
          align: "right",
        }),
      ]),

      rect({ x: 16, y: 254, w: w - 32, h: 28, fill: "#eef2fb", radius: 3 }),
      text({
        x: 24,
        y: 262,
        w: 96,
        h: 12,
        text: "3월 등록 시 교재비 면제",
        size: 12.5,
        weight: 700,
        color: INK.navy,
      }),
      text({
        x: 24,
        y: 272,
        w: 110,
        h: 6,
        text: "상담은 전화로 예약해 주세요. 수업 중에는 받지 못합니다.",
        size: 8.5,
        color: INK.soft,
      }),
      text({
        x: 132,
        y: 263,
        w: 56,
        h: 12,
        text: "02-338-0000",
        size: 13,
        weight: 700,
        color: INK.navy,
        align: "right",
        font: "gothic-a1",
      }),
    ],
  },

  /* ---------------------------------------------------------
     3. 필라테스 체험 — 사진을 아래로 내리고 위를 비웁니다 (양면)
     --------------------------------------------------------- */
  {
    id: "flyer-pilates-trial",
    name: "필라테스 체험",
    note: "위를 비우고 사진을 아래에. 뒷면은 수업 안내.",
    industry: "fitness",
    style: "photo",
    palette: ["mono", "ink"],
    art: ["flyer-fitness-photo"],
    tags: ["헬스", "체험", "양면"],
    background: { color: "#f4f4f5" },
    backgroundBack: { color: "#ffffff" },
    build: ({ w, bleed }) => [
      text({
        x: 18,
        y: 34,
        w: 100,
        h: 5,
        text: "PILATES STUDIO",
        size: 9,
        weight: 700,
        color: INK.grey,
        letterSpacing: 0.34,
        font: "gothic-a1",
      }),
      text({
        x: 18,
        y: 48,
        w: w - 36,
        h: 40,
        text: "처음 오신 분,\n1:1로 한 번\n해 보고 정하세요",
        size: 26,
        weight: 700,
        color: INK.black,
        lineHeight: 1.34,
        letterSpacing: -0.03,
        font: "gothic-a1",
      }),
      text({
        x: 18,
        y: 116,
        w: 104,
        h: 12,
        text: "몸을 먼저 봅니다. 자세를 재고, 어디가 굳었는지 확인한 뒤에\n무엇부터 할지 정합니다.",
        size: 10.5,
        color: INK.soft,
        lineHeight: 1.8,
      }),

      rect({ x: 18, y: 142, w: 74, h: 22, fill: INK.black, radius: 2 }),
      text({
        x: 18,
        y: 148,
        w: 74,
        h: 10,
        text: "1회 체험 20,000원",
        size: 12,
        weight: 700,
        color: "#ffffff",
        align: "center",
        font: "gothic-a1",
      }),
      text({
        x: 98,
        y: 148,
        w: 90,
        h: 10,
        text: "등록하시면 체험비는\n첫 달 수강료에서 뺍니다.",
        size: 9,
        color: INK.grey,
        lineHeight: 1.6,
      }),

      image("flyer-fitness-photo", {
        x: -bleed,
        y: 178,
        w: w + bleed * 2,
        h: 119 + bleed,
        focusY: 0.74,
      }),

      /* ── 뒷면 ── */
      text({
        side: "back",
        x: 18,
        y: 28,
        w: w - 36,
        h: 10,
        text: "수업 안내",
        size: 18,
        weight: 700,
        color: INK.black,
        font: "gothic-a1",
      }),
      rule({ side: "back", x: 18, y: 46, w: w - 36, fill: INK.black, h: 1 }),

      ...[
        ["개인 수업", "50분 · 1:1", "1회 70,000원"],
        ["듀엣", "50분 · 2인", "1회 45,000원"],
        ["그룹", "50분 · 4인까지", "1회 28,000원"],
        ["기구 8회권", "두 달 안에 사용", "480,000원"],
        ["매트 12회권", "석 달 안에 사용", "300,000원"],
      ].flatMap(([name, desc, price], i) =>
        priceRow({
          x: 18,
          y: 60 + i * 26,
          w: w - 36,
          name,
          desc,
          price,
          nameSize: 12.5,
          descSize: 9,
          priceWidth: 40,
          side: "back",
        }),
      ),

      rect({ side: "back", x: 18, y: 200, w: w - 36, h: 46, fill: "#f4f4f5", radius: 3 }),
      ...bullets({
        x: 26,
        y: 210,
        w: 150,
        size: 9.5,
        gap: 8,
        lines: [
          "수업은 예약제입니다. 하루 전까지 알려 주세요",
          "당일 취소는 1회 차감됩니다",
          "양말은 대여해 드립니다",
          "주차는 건물 뒤편에 두 시간 무료",
        ],
        side: "back",
      }),

      text({
        side: "back",
        x: 18,
        y: 262,
        w: w - 36,
        h: 12,
        text: "서울 강남구 선릉로 88, 3층 · 02-540-0000\n평일 07:00 – 22:00 · 토 09:00 – 15:00",
        size: 9.5,
        color: INK.grey,
        lineHeight: 1.8,
      }),
    ],
  },

  /* ---------------------------------------------------------
     4. 반찬가게 세일 — 수채화 띠를 아래에
     --------------------------------------------------------- */
  {
    id: "flyer-market-sale",
    name: "제철 할인",
    note: "수채화를 아래 띠로. 품목과 값이 한눈에 들어옵니다.",
    industry: "food",
    style: "watercolor",
    palette: ["green", "warm"],
    art: ["flyer-market-water"],
    tags: ["마트", "할인", "제철"],
    background: { color: "#fdfcf8" },
    build: ({ w, bleed }) => [
      text({
        x: 18,
        y: 30,
        w: w - 36,
        h: 5,
        text: "3월 한 달간",
        size: 11,
        weight: 700,
        color: INK.green,
        letterSpacing: 0.1,
      }),
      text({
        x: 18,
        y: 42,
        w: w - 36,
        h: 30,
        text: "제철 나물,\n스무 가지 20% 할인",
        size: 24,
        weight: 700,
        color: INK.green,
        lineHeight: 1.36,
        letterSpacing: -0.02,
        font: "gothic-a1",
      }),
      text({
        x: 18,
        y: 88,
        w: 112,
        h: 12,
        text: "새벽에 받아 그날 무칩니다. 남은 것은 다음 날 내놓지 않습니다.",
        size: 10.5,
        color: INK.soft,
        lineHeight: 1.8,
      }),

      rule({ x: 18, y: 112, w: w - 36, fill: "#dcd7c9" }),

      ...[
        ["시금치나물", "4,000", "3,200"],
        ["취나물 무침", "5,500", "4,400"],
        ["도라지 생채", "6,000", "4,800"],
        ["냉이 된장무침", "5,000", "4,000"],
      ].flatMap(([name, was, now], i) => [
        text({
          x: 18,
          y: 122 + i * 18,
          w: 70,
          h: 6,
          text: name,
          size: 12,
          weight: 700,
          color: INK.black,
        }),
        text({
          x: 96,
          y: 124 + i * 18,
          w: 34,
          h: 6,
          text: was,
          size: 10,
          color: INK.grey,
          align: "right",
        }),
        text({
          x: 138,
          y: 122 + i * 18,
          w: 54,
          h: 6,
          text: `${now}원`,
          size: 13,
          weight: 700,
          color: INK.red,
          align: "right",
          font: "gothic-a1",
        }),
      ]),

      text({
        x: 18,
        y: 198,
        w: w - 36,
        h: 6,
        text: "3만 원 이상 사시면 반경 2km 안은 배달해 드립니다.",
        size: 10,
        color: INK.soft,
      }),
      text({
        x: 18,
        y: 210,
        w: w - 36,
        h: 8,
        text: "성산반찬 · 마포구 성미산로 24 · 02-333-0000",
        size: 11,
        weight: 700,
        color: INK.green,
      }),

      image("flyer-market-water", {
        x: -bleed,
        y: 226,
        w: w + bleed * 2,
        h: 71 + bleed,
      }),
    ],
  },

  /* ---------------------------------------------------------
     5. 의원 개원 — 옅은 도형과 넉넉한 여백
     --------------------------------------------------------- */
  {
    id: "flyer-clinic-open",
    name: "의원 개원 안내",
    note: "차분한 색과 큰 여백. 진료 과목이 표처럼 읽힙니다.",
    industry: "clinic",
    style: "minimal",
    palette: ["pastel", "navy"],
    tags: ["병원", "개원", "진료시간"],
    background: { color: "#ffffff" },
    build: ({ w, h, bleed }) => [
      /* 색면은 그림이 아니라 도형입니다. 원 하나를 이미지로 받아 두면
         파일도 무겁고 사용자가 색을 못 바꿉니다. */
      ellipse({ x: 132, y: 26, w: 128, h: 128, fill: "#e3eef4" }),
      rect({ x: -bleed, y: h - 16, w: w + bleed * 2, h: 16 + bleed, fill: "#cfe8e3" }),

      text({
        x: 20,
        y: 32,
        w: w - 40,
        h: 5,
        text: "2026. 3. 9 개원",
        size: 10,
        weight: 700,
        color: INK.teal,
        letterSpacing: 0.16,
      }),
      text({
        x: 20,
        y: 46,
        w: w - 40,
        h: 24,
        text: "성산동에\n내과가 생겼습니다",
        size: 23,
        weight: 700,
        color: INK.black,
        lineHeight: 1.38,
        letterSpacing: -0.02,
        font: "gothic-a1",
      }),
      text({
        x: 20,
        y: 92,
        w: 104,
        h: 12,
        text: "감기부터 만성질환까지 봅니다. 오래 기다리지 않도록 예약제로\n운영합니다.",
        size: 10.5,
        color: INK.soft,
        lineHeight: 1.8,
      }),

      rule({ x: 20, y: 120, w: w - 40, fill: "#cfe0e0" }),

      text({
        x: 20,
        y: 130,
        w: 80,
        h: 6,
        text: "진료 과목",
        size: 9.5,
        weight: 700,
        color: INK.grey,
        letterSpacing: 0.1,
      }),
      text({
        x: 20,
        y: 140,
        w: 78,
        h: 20,
        text: "내과 · 소화기\n고혈압 · 당뇨\n건강검진\n예방접종",
        size: 12,
        color: INK.black,
        lineHeight: 1.9,
      }),

      text({
        x: 112,
        y: 130,
        w: 80,
        h: 6,
        text: "진료 시간",
        size: 9.5,
        weight: 700,
        color: INK.grey,
        letterSpacing: 0.1,
      }),
      text({
        x: 112,
        y: 140,
        w: 78,
        h: 20,
        text: "평일 09:00 – 18:00\n토요일 09:00 – 13:00\n점심 13:00 – 14:00\n일요일·공휴일 휴진",
        size: 11,
        color: INK.black,
        lineHeight: 1.9,
      }),

      rule({ x: 20, y: 192, w: w - 40, fill: "#cfe0e0" }),

      text({
        x: 20,
        y: 204,
        w: 110,
        h: 14,
        text: "성산내과의원",
        size: 17,
        weight: 700,
        color: INK.teal,
        font: "gothic-a1",
      }),
      text({
        x: 20,
        y: 220,
        w: 120,
        h: 12,
        text: "서울 마포구 성미산로 30, 2층\n지하철 6호선 망원역 2번 출구\n주차 30분 무료",
        size: 10,
        color: INK.soft,
        lineHeight: 1.8,
      }),
      text({
        x: 132,
        y: 206,
        w: 58,
        h: 12,
        text: "02-337-0000",
        size: 14,
        weight: 700,
        color: INK.black,
        align: "right",
        font: "gothic-a1",
      }),
      text({
        x: 132,
        y: 220,
        w: 58,
        h: 6,
        text: "예약 · 문의",
        size: 9,
        color: INK.grey,
        align: "right",
      }),
    ],
  },

  /* ---------------------------------------------------------
     6. 부동산 매물 — 활자만으로 짠 표
     --------------------------------------------------------- */
  {
    id: "flyer-realestate-list",
    name: "매물 안내",
    note: "사진 없이 활자와 선만으로. 값이 한 줄에 섭니다.",
    industry: "realestate",
    style: "type",
    palette: ["ink", "mono"],
    tags: ["부동산", "매물", "표"],
    background: { color: "#ffffff" },
    build: ({ w, bleed }) => [
      rect({ x: -bleed, y: -bleed, w: w + bleed * 2, h: 8 + bleed, fill: INK.black }),

      text({
        x: 18,
        y: 30,
        w: w - 36,
        h: 5,
        text: "성산동 · 망원동 · 연남동",
        size: 10,
        weight: 700,
        color: INK.grey,
        letterSpacing: 0.12,
      }),
      text({
        x: 18,
        y: 42,
        w: w - 36,
        h: 24,
        text: "이번 주 나온 집",
        size: 27,
        weight: 700,
        color: INK.black,
        letterSpacing: -0.03,
        font: "gothic-a1",
      }),
      rule({ x: 18, y: 76, w: w - 36, fill: INK.black, h: 1.2 }),

      ...[
        ["성산동 빌라 3층", "전용 59㎡ · 방 3", "전세 3억 2,000"],
        ["망원 리버뷰 12층", "전용 84㎡ · 방 3", "매매 9억 5,000"],
        ["연남 신축 원룸", "전용 23㎡ · 분리형", "월세 1,000 / 65"],
        ["성산 상가 1층", "전용 33㎡ · 코너", "월세 3,000 / 180"],
        ["망원 주택 2층", "전용 76㎡ · 마당", "매매 7억 2,000"],
      ].flatMap(([name, spec, price], i) => [
        text({
          x: 18,
          y: 88 + i * 26,
          w: 86,
          h: 6,
          text: name,
          size: 12.5,
          weight: 700,
          color: INK.black,
        }),
        text({
          x: 18,
          y: 98 + i * 26,
          w: 86,
          h: 6,
          text: spec,
          size: 9.5,
          color: INK.grey,
        }),
        text({
          x: 110,
          y: 89 + i * 26,
          w: 82,
          h: 8,
          text: price,
          size: 13,
          weight: 700,
          color: INK.black,
          align: "right",
          font: "gothic-a1",
        }),
        rule({ x: 18, y: 108 + i * 26, w: w - 36, fill: INK.line }),
      ]),

      text({
        x: 18,
        y: 228,
        w: 116,
        h: 12,
        text: "매물은 매주 월요일에 새로 붙입니다. 찾는 조건을 남겨 두시면\n나오는 대로 연락드립니다.",
        size: 10,
        color: INK.soft,
        lineHeight: 1.8,
      }),

      rect({ x: 18, y: 254, w: w - 36, h: 28, fill: INK.black, radius: 2 }),
      text({
        x: 26,
        y: 262,
        w: 90,
        h: 10,
        text: "성산공인중개사사무소",
        size: 12,
        weight: 700,
        color: "#ffffff",
      }),
      text({
        x: 118,
        y: 261,
        w: 68,
        h: 10,
        text: "02-334-0000",
        size: 15,
        weight: 700,
        color: "#ffffff",
        align: "right",
        font: "gothic-a1",
      }),
      text({
        x: 26,
        y: 272,
        w: 160,
        h: 6,
        text: "마포구 성미산로 18 · 평일 09:00 – 19:00 · 일요일 휴무",
        size: 8.5,
        color: "#a1a1aa",
      }),
    ],
  },

  /* ---------------------------------------------------------
     7. 교회 초청 — 수채화와 명조
     --------------------------------------------------------- */
  {
    id: "flyer-church-invite",
    name: "부활절 초청",
    note: "명조와 수채화. 초청하는 인쇄물에 어울리는 온도.",
    industry: "community",
    style: "watercolor",
    palette: ["warm", "pastel"],
    art: ["poster-church-water"],
    tags: ["교회", "초청", "행사"],
    background: artBackground("poster-church-water", "#fbf8f3", 0.5),
    build: ({ w }) => [
      text({
        x: 22,
        y: 40,
        w: w - 44,
        h: 5,
        text: "2026 부활절 초청",
        size: 10,
        weight: 700,
        color: INK.gold,
        letterSpacing: 0.22,
        align: "center",
      }),
      text({
        x: 22,
        y: 56,
        w: w - 44,
        h: 34,
        text: "봄이 오면\n다시 만나기로 했습니다",
        size: 22,
        weight: 700,
        color: "#4a3b2a",
        align: "center",
        lineHeight: 1.5,
        font: "nanum-myeongjo",
      }),
      rule({ x: 88, y: 106, w: w - 176, fill: "#d9cbb4", h: 0.6 }),

      text({
        x: 34,
        y: 122,
        w: w - 68,
        h: 18,
        text: "혼자 오셔도 좋고, 오래 안 나오셨어도 좋습니다.\n예배가 끝나면 마당에서 국수를 나눕니다.\n처음 오신 분께는 작은 화분을 드립니다.",
        size: 11,
        color: "#5b4a37",
        align: "center",
        lineHeight: 2,
        font: "nanum-myeongjo",
      }),

      text({
        x: 34,
        y: 186,
        w: w - 68,
        h: 22,
        text: "4월 5일 주일\n오전 11시",
        size: 19,
        weight: 700,
        color: "#4a3b2a",
        align: "center",
        lineHeight: 1.5,
        font: "nanum-myeongjo",
      }),

      rule({ x: 88, y: 226, w: w - 176, fill: "#d9cbb4", h: 0.6 }),
      text({
        x: 22,
        y: 238,
        w: w - 44,
        h: 16,
        text: "성산교회\n서울 마포구 성미산로 40 · 02-335-0000\n망원역 2번 출구에서 걸어서 5분",
        size: 10,
        color: "#6b5a45",
        align: "center",
        lineHeight: 1.9,
        font: "nanum-myeongjo",
      }),
    ],
  },

  /* ---------------------------------------------------------
     8. 치킨집 신메뉴 — 색면 대비로 크게
     --------------------------------------------------------- */
  {
    id: "flyer-chicken-new",
    name: "신메뉴 출시",
    note: "붉은 색면과 굵은 제목. 배달 전단에 맞는 세기.",
    industry: "food",
    style: "bold",
    palette: ["red", "ink"],
    tags: ["음식점", "신메뉴", "배달"],
    background: { color: "#1a1a1a" },
    build: ({ w, bleed }) => [
      rect({ x: -bleed, y: -bleed, w: w + bleed * 2, h: 132 + bleed, fill: INK.red }),
      ellipse({ x: 128, y: 18, w: 96, h: 96, fill: "#ffffff", opacity: 0.1 }),

      text({
        x: 18,
        y: 26,
        w: 120,
        h: 5,
        text: "NEW",
        size: 11,
        weight: 700,
        color: "#ffd9d9",
        letterSpacing: 0.4,
        font: "black-han-sans",
      }),
      text({
        x: 18,
        y: 40,
        w: 150,
        h: 44,
        text: "간장 한 마리,\n오늘부터",
        size: 34,
        weight: 400,
        color: "#ffffff",
        lineHeight: 1.3,
        font: "black-han-sans",
      }),
      text({
        x: 18,
        y: 102,
        w: 120,
        h: 10,
        text: "이십 년 끓인 간장에 하루 재웁니다",
        size: 11,
        color: "#ffd9d9",
      }),

      rect({ x: 18, y: 150, w: 84, h: 40, fill: "#252525", radius: 3 }),
      text({
        x: 18,
        y: 158,
        w: 84,
        h: 8,
        text: "한 마리",
        size: 11,
        color: "#a1a1aa",
        align: "center",
      }),
      text({
        x: 18,
        y: 168,
        w: 84,
        h: 14,
        text: "19,000원",
        size: 19,
        weight: 400,
        color: "#ffffff",
        align: "center",
        font: "black-han-sans",
      }),
      rect({ x: 108, y: 150, w: 84, h: 40, fill: "#252525", radius: 3 }),
      text({
        x: 108,
        y: 158,
        w: 84,
        h: 8,
        text: "두 마리",
        size: 11,
        color: "#a1a1aa",
        align: "center",
      }),
      text({
        x: 108,
        y: 168,
        w: 84,
        h: 14,
        text: "34,000원",
        size: 19,
        weight: 400,
        color: "#ffd166",
        align: "center",
        font: "black-han-sans",
      }),

      ...bullets({
        x: 18,
        y: 204,
        w: 160,
        size: 10.5,
        gap: 9,
        color: "#a1a1aa",
        lines: [
          "치킨무·콜라 포함",
          "배달은 반경 3km 까지",
          "매일 16:00 – 02:00 (연중무휴)",
        ],
      }),

      rule({ x: 18, y: 244, w: w - 36, fill: "#3f3f46" }),
      text({
        x: 18,
        y: 254,
        w: 100,
        h: 14,
        text: "성산치킨",
        size: 18,
        weight: 400,
        color: "#ffffff",
        font: "black-han-sans",
      }),
      text({
        x: 100,
        y: 254,
        w: 92,
        h: 14,
        text: "02-339-0000",
        size: 20,
        weight: 400,
        color: "#ffd166",
        align: "right",
        font: "black-han-sans",
      }),
      text({
        x: 18,
        y: 274,
        w: w - 36,
        h: 6,
        text: "서울 마포구 성미산로 8 · 배달앱에서도 주문하실 수 있습니다",
        size: 8.5,
        color: "#a1a1aa",
      }),
    ],
  },
];

export const FLYER_TEMPLATES = composeAll("flyer", DRAFTS);
