/**
 * 포스터 여덟 장.
 *
 * 포스터는 벽에 붙어 있고, 사람은 지나가면서 봅니다. 그래서 전단지와
 * 반대로 짭니다 — 정보를 줄이고 제목을 키웁니다. 여덟 장 모두 «열 걸음
 * 밖에서 읽히는 것» 을 첫 조건으로 두었고, 그 아래 붙는 날짜·장소·값은
 * 가까이 온 사람을 위한 두 번째 층입니다.
 *
 * A3(297×420)가 기본입니다. 안전선이 5mm 라 다른 갈래보다 넓고, 벽에
 * 붙이면 아래쪽이 가려지는 일이 많아 중요한 것을 아래 40mm 안에 두지
 * 않았습니다.
 */

import {
  INK,
  artBackground,
  bullets,
  composeAll,
  ellipse,
  image,
  rect,
  rule,
  text,
  type Draft,
} from "@/lib/print/templates/kit";

const DRAFTS: Draft[] = [
  /* ---------------------------------------------------------
     1. 공연 — 어두운 사진 위에 흰 활자
     --------------------------------------------------------- */
  {
    id: "poster-concert-night",
    name: "밤 공연",
    note: "어두운 사진 한 장 위에 활자만. 공연 포스터의 기본형.",
    industry: "event",
    style: "photo",
    palette: ["ink", "mono"],
    art: ["poster-concert-photo"],
    tags: ["공연", "음악회", "행사"],
    background: { color: "#0b0f14" },
    build: ({ w, h, bleed }) => [
      image("poster-concert-photo", {
        x: -bleed,
        y: -bleed,
        w: w + bleed * 2,
        h: h + bleed * 2,
        brightness: 116,
      }),
      /* 무대가 사진의 60% 지점에 있습니다. 막을 그 위에 씌우면 사진에서
         가장 좋은 부분이 사라지므로, 객석 쪽에만 깝니다. */
      rect({ x: -bleed, y: 296, w: w + bleed * 2, h: 124 + bleed, fill: "#0b0f14", opacity: 0.78 }),

      text({
        x: 24,
        y: 40,
        w: w - 48,
        h: 6,
        text: "성산문화재단 기획공연",
        size: 11,
        weight: 700,
        color: "#8fb6d9",
        letterSpacing: 0.22,
      }),
      text({
        x: 24,
        y: 60,
        w: w - 48,
        h: 100,
        text: "밤에\n듣는\n실내악",
        size: 74,
        weight: 700,
        color: "#ffffff",
        lineHeight: 1.12,
        letterSpacing: -0.04,
        font: "gothic-a1",
      }),

      rule({ x: 24, y: 308, w: w - 48, fill: "#3a4a5c", h: 0.8 }),

      text({
        x: 24,
        y: 320,
        w: 150,
        h: 30,
        text: "8월 12일 금요일\n저녁 7시 30분",
        size: 20,
        weight: 700,
        color: "#ffffff",
        lineHeight: 1.5,
        font: "gothic-a1",
      }),
      text({
        x: 24,
        y: 312,
        w: 150,
        h: 20,
        text: "성산아트홀 소극장\n전석 20,000원 (학생 12,000원)",
        size: 12,
        color: "#c3d2e0",
        lineHeight: 1.8,
      }),

      ...bullets({
        x: 180,
        y: 322,
        w: 92,
        size: 11,
        gap: 9,
        color: "#8fa4b8",
        lines: [
          "현악사중주 · 피아노 삼중주",
          "1부 45분 · 휴식 15분 · 2부 40분",
          "미취학 아동은 입장이 어렵습니다",
          "공연 시작 후에는 입장이 제한됩니다",
        ],
      }),

      rule({ x: 24, y: 392, w: w - 48, fill: "#3a4a5c", h: 0.8 }),
      text({
        x: 24,
        y: 400,
        w: w - 48,
        h: 10,
        text: "예매 cardly.kr · 문의 02-330-0000 · 주최 성산문화재단",
        size: 10.5,
        color: "#7d90a3",
      }),
    ],
  },

  /* ---------------------------------------------------------
     2. 축제 — 플랫 일러스트를 아래에 깔고 하늘을 비웁니다
     --------------------------------------------------------- */
  {
    id: "poster-festival-night",
    name: "동네 축제",
    note: "일러스트를 아래에 깔고 하늘을 비웠습니다. 제목이 하늘에 섭니다.",
    industry: "event",
    style: "flat",
    palette: ["navy", "warm"],
    art: ["poster-festival-flat"],
    tags: ["축제", "행사", "야시장"],
    background: { color: "#122036" },
    build: ({ w, bleed }) => [
      image("poster-festival-flat", {
        x: -bleed,
        y: 208,
        w: w + bleed * 2,
        h: 212 + bleed,
      }),

      text({
        x: 24,
        y: 44,
        w: w - 48,
        h: 6,
        text: "제7회 성산동 밤마실",
        size: 12,
        weight: 700,
        color: "#f2c14e",
        letterSpacing: 0.16,
        align: "center",
      }),
      text({
        x: 20,
        y: 68,
        w: w - 40,
        h: 76,
        text: "골목에\n불이 켜지면",
        size: 58,
        weight: 700,
        color: "#ffffff",
        align: "center",
        lineHeight: 1.24,
        letterSpacing: -0.03,
        font: "gothic-a1",
      }),
      text({
        x: 40,
        y: 176,
        w: w - 80,
        h: 16,
        text: "먹거리 스물여덟 집, 마당 무대, 그리고 밤 열한 시까지",
        size: 13,
        color: "#c9d6e8",
        align: "center",
        lineHeight: 1.8,
      }),

      rect({ x: 62, y: 202, w: w - 124, h: 34, fill: "#f2c14e", radius: 4 }),
      text({
        x: 62,
        y: 212,
        w: w - 124,
        h: 14,
        text: "10월 4일 토요일 오후 5시 – 밤 11시",
        size: 15,
        weight: 700,
        color: "#122036",
        align: "center",
        font: "gothic-a1",
      }),

      text({
        x: 24,
        y: 384,
        w: w - 48,
        h: 10,
        text: "성산동 문화의거리 일대 · 주최 성산동 상인회 · 문의 02-330-0000",
        size: 10.5,
        color: "#ffffff",
        align: "center",
      }),
    ],
  },

  /* ---------------------------------------------------------
     3. 아르바이트 모집 — 종이 질감에 활자만
     --------------------------------------------------------- */
  {
    id: "poster-recruit-part",
    name: "직원 모집",
    note: "종이 질감 위에 활자만. 조건이 표처럼 읽힙니다.",
    industry: "sale",
    style: "type",
    palette: ["mono", "ink"],
    art: ["poster-recruit-texture"],
    tags: ["모집", "채용", "공고"],
    background: artBackground("poster-recruit-texture", "#f4f2ec", 0.85),
    build: ({ w }) => [
      text({
        x: 26,
        y: 44,
        w: w - 52,
        h: 6,
        text: "성산국밥 · 함께 일할 분을 찾습니다",
        size: 12,
        weight: 700,
        color: INK.grey,
        letterSpacing: 0.08,
      }),
      rule({ x: 26, y: 58, w: w - 52, fill: INK.black, h: 1.4 }),

      text({
        x: 26,
        y: 74,
        w: w - 52,
        h: 62,
        text: "홀 서빙\n주 5일",
        size: 58,
        weight: 700,
        color: INK.black,
        lineHeight: 1.2,
        letterSpacing: -0.04,
        font: "gothic-a1",
      }),

      rule({ x: 26, y: 190, w: w - 52, fill: INK.line }),

      ...[
        ["근무 시간", "오전 10시 – 오후 4시 (휴게 1시간)"],
        ["근무 요일", "월요일 – 금요일, 주말 휴무"],
        ["급여", "시급 12,000원 · 매월 10일 지급"],
        ["우대", "인근 거주 · 장기 근무 가능하신 분"],
        ["식사", "점심 제공"],
      ].flatMap(([label, value], i) => [
        text({
          x: 26,
          y: 202 + i * 26,
          w: 54,
          h: 8,
          text: label,
          size: 12,
          weight: 700,
          color: INK.grey,
        }),
        text({
          x: 88,
          y: 202 + i * 26,
          w: w - 114,
          h: 8,
          text: value,
          size: 14,
          color: INK.black,
        }),
        rule({ x: 26, y: 218 + i * 26, w: w - 52, fill: "#dedbd3" }),
      ]),

      text({
        x: 26,
        y: 348,
        w: w - 52,
        h: 12,
        text: "전화 주시고 편한 시간에 오시면 됩니다. 이력서는 없어도 괜찮습니다.",
        size: 12,
        color: INK.soft,
      }),
      rect({ x: 26, y: 366, w: w - 52, h: 30, fill: INK.black }),
      text({
        x: 26,
        y: 375,
        w: w - 52,
        h: 12,
        text: "02-331-0000 · 마포구 성미산로 16",
        size: 16,
        weight: 700,
        color: "#ffffff",
        align: "center",
        font: "gothic-a1",
      }),
    ],
  },

  /* ---------------------------------------------------------
     4. 학원 설명회 — 색면 두 개로 나눈 판
     --------------------------------------------------------- */
  {
    id: "poster-academy-brief",
    name: "입시 설명회",
    note: "위아래를 색으로 나눠 제목과 정보를 분리했습니다.",
    industry: "academy",
    style: "minimal",
    palette: ["navy", "mono"],
    tags: ["학원", "설명회", "모집"],
    background: { color: "#ffffff" },
    build: ({ w, bleed }) => [
      rect({ x: -bleed, y: -bleed, w: w + bleed * 2, h: 232 + bleed, fill: INK.navy }),

      text({
        x: 26,
        y: 46,
        w: w - 52,
        h: 6,
        text: "2027 대입 · 학부모 설명회",
        size: 12,
        weight: 700,
        color: "#9db4d9",
        letterSpacing: 0.16,
      }),
      text({
        x: 26,
        y: 70,
        w: w - 52,
        h: 90,
        text: "무엇을\n먼저 정해야\n하는가",
        size: 56,
        weight: 700,
        color: "#ffffff",
        lineHeight: 1.24,
        letterSpacing: -0.04,
        font: "gothic-a1",
      }),
      text({
        x: 26,
        y: 188,
        w: 200,
        h: 16,
        text: "학년별로 지금 결정해야 하는 것과 미뤄도 되는 것을 나눠 드립니다.\n작년 합격 사례를 숫자로 보여 드립니다.",
        size: 12,
        color: "#c5d3e8",
        lineHeight: 1.85,
      }),

      text({
        x: 26,
        y: 254,
        w: 150,
        h: 28,
        text: "3월 15일 토요일\n오전 10시",
        size: 22,
        weight: 700,
        color: INK.navy,
        lineHeight: 1.5,
        font: "gothic-a1",
      }),
      rule({ x: 26, y: 306, w: w - 52, fill: INK.line }),

      ...[
        ["장소", "성산에듀 학습관 3층 강당"],
        ["대상", "예비 고1 – 고3 학부모"],
        ["정원", "선착순 60명 · 사전 예약"],
        ["자료", "학년별 로드맵 책자 배부"],
      ].flatMap(([label, value], i) => [
        text({
          x: 26,
          y: 318 + i * 20,
          w: 34,
          h: 7,
          text: label,
          size: 11,
          weight: 700,
          color: INK.grey,
        }),
        text({
          x: 68,
          y: 318 + i * 20,
          w: w - 94,
          h: 7,
          text: value,
          size: 12.5,
          color: INK.black,
        }),
      ]),

      rect({ x: 26, y: 400, w: w - 52, h: 0, fill: INK.navy }),
      text({
        x: 26,
        y: 404,
        w: w - 52,
        h: 8,
        text: "예약 02-338-0000 · 마포구 성미산로 22",
        size: 12,
        weight: 700,
        color: INK.navy,
      }),
    ],
  },

  /* ---------------------------------------------------------
     5. 예방접종 — 옅은 도형, 안내문의 온도
     --------------------------------------------------------- */
  {
    id: "poster-clinic-vaccine",
    name: "예방접종 안내",
    note: "차분한 색과 큰 여백. 병원 벽에 붙이는 안내문.",
    industry: "clinic",
    style: "minimal",
    palette: ["pastel", "green"],
    tags: ["병원", "안내", "접종"],
    background: { color: "#ffffff" },
    build: ({ w, h, bleed }) => [
      ellipse({ x: 186, y: 150, w: 190, h: 190, fill: "#dbe9f0" }),
      rect({ x: -bleed, y: h - 18, w: w + bleed * 2, h: 18 + bleed, fill: "#cfe8e3" }),

      text({
        x: 28,
        y: 52,
        w: w - 56,
        h: 6,
        text: "2026 – 2027 절기",
        size: 12,
        weight: 700,
        color: INK.teal,
        letterSpacing: 0.14,
      }),
      text({
        x: 28,
        y: 74,
        w: w - 56,
        h: 76,
        text: "독감 예방접종,\n지금 하시면 됩니다",
        size: 44,
        weight: 700,
        color: INK.black,
        lineHeight: 1.3,
        letterSpacing: -0.03,
        font: "gothic-a1",
      }),
      text({
        x: 28,
        y: 178,
        w: 190,
        h: 20,
        text: "예방접종은 맞고 나서 효과가 나기까지 2주가 걸립니다.\n유행이 시작되기 전에 맞으시는 편이 좋습니다.",
        size: 13,
        color: INK.soft,
        lineHeight: 1.9,
      }),

      rect({ x: 28, y: 226, w: (w - 66) / 2, h: 76, fill: "#eef7f5", radius: 4 }),
      text({
        x: 40,
        y: 240,
        w: (w - 66) / 2 - 24,
        h: 7,
        text: "무료 대상",
        size: 12,
        weight: 700,
        color: INK.teal,
      }),
      text({
        x: 40,
        y: 254,
        w: (w - 66) / 2 - 24,
        h: 34,
        text: "생후 6개월 – 13세\n임신부\n65세 이상",
        size: 13,
        color: INK.black,
        lineHeight: 1.85,
      }),

      rect({ x: 28 + (w - 66) / 2 + 10, y: 226, w: (w - 66) / 2, h: 76, fill: "#f5f5f4", radius: 4 }),
      text({
        x: 40 + (w - 66) / 2 + 10,
        y: 240,
        w: (w - 66) / 2 - 24,
        h: 7,
        text: "일반",
        size: 12,
        weight: 700,
        color: INK.grey,
      }),
      text({
        x: 40 + (w - 66) / 2 + 10,
        y: 254,
        w: (w - 66) / 2 - 24,
        h: 34,
        text: "3가 35,000원\n4가 45,000원\n예약 없이 오셔도 됩니다",
        size: 13,
        color: INK.black,
        lineHeight: 1.85,
      }),

      rule({ x: 28, y: 326, w: w - 56, fill: "#cfe0dd" }),
      text({
        x: 28,
        y: 340,
        w: 160,
        h: 20,
        text: "성산내과의원\n마포구 성미산로 30, 2층",
        size: 15,
        weight: 700,
        color: INK.teal,
        lineHeight: 1.6,
        font: "gothic-a1",
      }),
      text({
        x: 190,
        y: 340,
        w: w - 218,
        h: 20,
        text: "평일 09:00 – 18:00\n토요일 09:00 – 13:00\n02-337-0000",
        size: 12,
        color: INK.soft,
        align: "right",
        lineHeight: 1.7,
      }),
    ],
  },

  /* ---------------------------------------------------------
     6. 교회 부활절 — 수채화와 명조, 가운데 정렬
     --------------------------------------------------------- */
  {
    id: "poster-church-easter",
    name: "부활절 예배",
    note: "수채화와 명조. 가운데로 모아 초청하는 인상.",
    industry: "community",
    style: "watercolor",
    palette: ["warm", "pastel"],
    art: ["poster-church-water"],
    tags: ["교회", "행사", "초청"],
    background: artBackground("poster-church-water", "#fbf7f0", 0.7),
    build: ({ w }) => [
      text({
        x: 30,
        y: 58,
        w: w - 60,
        h: 6,
        text: "2026 부활절 연합예배",
        size: 12,
        weight: 700,
        color: "#a1762f",
        letterSpacing: 0.24,
        align: "center",
      }),
      rule({ x: w / 2 - 14, y: 76, w: 28, fill: "#c8ab77", h: 0.8 }),

      text({
        x: 26,
        y: 96,
        w: w - 52,
        h: 84,
        text: "다시\n봄이 왔습니다",
        size: 46,
        weight: 700,
        color: "#4a3b2a",
        align: "center",
        lineHeight: 1.42,
        font: "nanum-myeongjo",
      }),

      text({
        x: 48,
        y: 206,
        w: w - 96,
        h: 26,
        text: "오래 나오지 않으셨어도 괜찮습니다.\n예배가 끝나면 마당에서 국수를 나눕니다.",
        size: 13.5,
        color: "#6b5a45",
        align: "center",
        lineHeight: 2.1,
        font: "nanum-myeongjo",
      }),

      ellipse({ x: w / 2 - 46, y: 258, w: 92, h: 92, fill: "transparent", stroke: "#c8ab77", strokeWidth: 0.6 }),
      text({
        x: w / 2 - 46,
        y: 282,
        w: 92,
        h: 34,
        text: "4월 5일\n주일 11시",
        size: 17,
        weight: 700,
        color: "#4a3b2a",
        align: "center",
        lineHeight: 1.6,
        font: "nanum-myeongjo",
      }),

      rule({ x: 70, y: 372, w: w - 140, fill: "#ddcdb2", h: 0.6 }),
      text({
        x: 30,
        y: 384,
        w: w - 60,
        h: 16,
        text: "성산교회 · 마포구 성미산로 40 · 02-335-0000\n망원역 2번 출구에서 걸어서 5분",
        size: 11,
        color: "#6b5a45",
        align: "center",
        lineHeight: 1.9,
        font: "nanum-myeongjo",
      }),
    ],
  },

  /* ---------------------------------------------------------
     7. 창고 대방출 — 세기로 미는 판
     --------------------------------------------------------- */
  {
    id: "poster-sale-clearance",
    name: "창고 대방출",
    note: "숫자를 화면 절반까지 키웠습니다. 세일 포스터의 문법.",
    industry: "sale",
    style: "bold",
    palette: ["red", "warm"],
    tags: ["세일", "할인", "행사"],
    background: { color: "#f7e9d0" },
    build: ({ w, bleed }) => [
      rect({ x: -bleed, y: 250, w: w + bleed * 2, h: 170 + bleed, fill: "#b91c1c" }),

      text({
        x: 24,
        y: 46,
        w: w - 48,
        h: 8,
        text: "이월 상품 창고 대방출 · 사흘만",
        size: 13,
        weight: 700,
        color: "#b91c1c",
        letterSpacing: 0.1,
      }),

      text({
        x: 20,
        y: 66,
        w: w - 40,
        h: 120,
        text: "최대",
        size: 34,
        weight: 400,
        color: "#7a1414",
        font: "black-han-sans",
      }),
      text({
        x: 20,
        y: 92,
        w: w - 40,
        h: 120,
        text: "70%",
        size: 128,
        weight: 400,
        color: "#b91c1c",
        lineHeight: 1,
        letterSpacing: -0.05,
        font: "black-han-sans",
      }),
      text({
        x: 20,
        y: 196,
        w: w - 40,
        h: 24,
        text: "전 품목 할인",
        size: 40,
        weight: 400,
        color: "#7a1414",
        font: "black-han-sans",
      }),

      text({
        x: 24,
        y: 268,
        w: w - 48,
        h: 24,
        text: "3월 6일 – 8일 · 오전 10시 – 밤 9시",
        size: 22,
        weight: 400,
        color: "#ffffff",
        font: "black-han-sans",
      }),

      ...bullets({
        x: 24,
        y: 304,
        w: w - 48,
        size: 12.5,
        gap: 11,
        color: "#ffd9d9",
        lines: [
          "이월 의류 · 신발 · 가방 전 품목",
          "교환과 환불은 어렵습니다",
          "카드 결제 가능 · 현금영수증 발행",
        ],
      }),

      rule({ x: 24, y: 356, w: w - 48, fill: "#d97070", h: 0.8 }),
      text({
        x: 24,
        y: 370,
        w: w - 48,
        h: 20,
        text: "성산아울렛 · 마포구 성미산로 44\n02-333-0000",
        size: 13,
        color: "#ffe0e0",
        lineHeight: 1.7,
      }),
    ],
  },

  /* ---------------------------------------------------------
     8. 헬스장 오픈 — 사진 위 흰 띠
     --------------------------------------------------------- */
  {
    id: "poster-fitness-open",
    name: "피트니스 오픈",
    note: "사진 위에 흰 띠 하나. 값이 가장 크게 읽힙니다.",
    industry: "fitness",
    style: "photo",
    palette: ["mono", "ink"],
    art: ["flyer-fitness-photo"],
    tags: ["헬스", "오픈", "등록"],
    background: { color: "#111111" },
    build: ({ w, bleed }) => [
      image("flyer-fitness-photo", {
        x: -bleed,
        y: -bleed,
        w: w + bleed * 2,
        h: 250 + bleed,
        focusY: 0.72,
        brightness: 88,
      }),

      rect({ x: 0, y: 168, w: 150, h: 46, fill: "#ffffff" }),
      text({
        x: 14,
        y: 180,
        w: 122,
        h: 12,
        text: "3월 2일 오픈",
        size: 20,
        weight: 700,
        color: INK.black,
        font: "gothic-a1",
      }),
      text({
        x: 14,
        y: 198,
        w: 122,
        h: 8,
        text: "성산 피트니스 & 필라테스",
        size: 10.5,
        color: INK.grey,
      }),

      text({
        x: 26,
        y: 276,
        w: w - 52,
        h: 60,
        text: "오픈 회원\n6개월 39만원",
        size: 44,
        weight: 700,
        color: "#ffffff",
        lineHeight: 1.3,
        letterSpacing: -0.03,
        font: "gothic-a1",
      }),
      text({
        x: 26,
        y: 344,
        w: 180,
        h: 14,
        text: "선착순 100명 · 정가 58만원\nGX·필라테스 그룹수업 무제한 포함",
        size: 13,
        color: "#a1a1aa",
        lineHeight: 1.8,
      }),

      rule({ x: 26, y: 380, w: w - 52, fill: "#3f3f46" }),
      text({
        x: 26,
        y: 392,
        w: w - 52,
        h: 10,
        text: "마포구 성미산로 50, 지하 1층 · 02-541-0000 · 24시간 운영",
        size: 11,
        color: "#8a8a8a",
      }),
    ],
  },
];

export const POSTER_TEMPLATES = composeAll("poster", DRAFTS);
