/**
 * 배너(X배너·롤업) 여덟 장.
 *
 * 세로로 길고, 사람 키만 합니다. 그래서 짜임이 하나로 정해집니다.
 *
 *   위   눈높이보다 위 — 제목. 멀리서 이것만 읽힙니다
 *   가운데 눈높이 — 그림이나 큰 정보
 *   아래  허리 아래 — 연락처. 가까이 온 사람만 봅니다
 *
 * 기본 규격은 X배너 600 × 1800mm 입니다. 아래 200mm 는 거치대와 사람에
 * 가려지므로 여덟 장 모두 그 안에 중요한 것을 두지 않았습니다.
 */

import {
  INK,
  bullets,
  composeAll,
  ellipse,
  image,
  rect,
  rule,
  text,
  type Draft,
} from "@/lib/print/templates/kit";

const DRAFTS: Draft[] = [
  /* ---------------------------------------------------------
     1. 부동산 — 사진을 가운데 창처럼
     --------------------------------------------------------- */
  {
    id: "sb-realestate",
    name: "분양 안내 배너",
    note: "가운데를 사진 창으로. 위는 제목, 아래는 조건과 전화.",
    industry: "realestate",
    style: "photo",
    palette: ["navy", "mono"],
    art: ["sb-realestate-photo"],
    tags: ["부동산", "분양", "모델하우스"],
    background: { color: "#ffffff" },
    build: ({ w, bleed }) => [
      rect({ x: -bleed, y: -bleed, w: w + bleed * 2, h: 470 + bleed, fill: INK.navy }),

      text({
        x: 60,
        y: 130,
        w: w - 120,
        h: 40,
        text: "성산 리버뷰 오피스텔",
        size: 62,
        weight: 700,
        color: "#9db4d9",
        letterSpacing: 0.06,
        font: "gothic-a1",
      }),
      text({
        x: 60,
        y: 210,
        w: w - 120,
        h: 200,
        text: "한강이\n보이는 집",
        size: 132,
        weight: 700,
        color: "#ffffff",
        lineHeight: 1.28,
        letterSpacing: -0.03,
        font: "gothic-a1",
      }),

      image("sb-realestate-photo", { x: 0, y: 470, w, h: 620 }),

      text({
        x: 60,
        y: 1150,
        w: w - 120,
        h: 60,
        text: "전세 3억 2,000 / 매매 6억",
        size: 78,
        weight: 700,
        color: INK.navy,
        font: "gothic-a1",
      }),
      rule({ x: 60, y: 1240, w: w - 120, fill: INK.line, h: 1 }),

      ...bullets({
        x: 60,
        y: 1270,
        w: w - 120,
        size: 40,
        gap: 62,
        color: INK.soft,
        lines: [
          "전용 59㎡ · 방 3 · 화장실 2",
          "즉시 입주 · 주차 세대당 1대",
          "망원역 도보 6분 · 초등학교 앞",
        ],
      }),

      rect({ x: 60, y: 1490, w: w - 120, h: 130, fill: INK.navy, radius: 8 }),
      text({
        x: 60,
        y: 1522,
        w: w - 120,
        h: 60,
        text: "02-334-0000",
        size: 74,
        weight: 700,
        color: "#ffffff",
        align: "center",
        font: "gothic-a1",
      }),
      text({
        x: 60,
        y: 1650,
        w: w - 120,
        h: 40,
        text: "성산공인중개사사무소 · 마포구 성미산로 18",
        size: 32,
        color: INK.grey,
        align: "center",
      }),
    ],
  },

  /* ---------------------------------------------------------
     2. 미용실 — 수채화가 오른쪽을 타고 내려옵니다
     --------------------------------------------------------- */
  {
    id: "sb-beauty-salon",
    name: "살롱 안내 배너",
    note: "수채화가 오른쪽을 타고 내려오고, 글자는 왼쪽에 붙습니다.",
    industry: "beauty",
    style: "watercolor",
    palette: ["pastel", "ink"],
    art: ["sb-beauty-water"],
    tags: ["미용실", "가격표", "오픈"],
    background: { color: "#fdfaf8" },
    build: ({ w, h, bleed }) => [
      image("sb-beauty-water", {
        x: -bleed,
        y: -bleed,
        w: w + bleed * 2,
        h: h + bleed * 2,
        opacity: 0.9,
      }),

      text({
        x: 56,
        y: 150,
        w: 300,
        h: 34,
        text: "SALON 여백",
        size: 46,
        weight: 700,
        color: "#a8748a",
        letterSpacing: 0.18,
        font: "gothic-a1",
      }),
      text({
        x: 56,
        y: 216,
        w: 400,
        h: 170,
        text: "머리를\n맡기는 일",
        size: 112,
        weight: 700,
        color: "#4a3a40",
        lineHeight: 1.32,
        letterSpacing: -0.03,
        font: "gothic-a1",
      }),
      text({
        x: 56,
        y: 430,
        w: 360,
        h: 90,
        text: "열두 해 같은 자리에서\n같은 손으로 합니다.",
        size: 40,
        color: "#6b5560",
        lineHeight: 1.9,
      }),

      rule({ x: 56, y: 580, w: 300, fill: "#e3d3d8", h: 1 }),

      ...[
        ["커트", "25,000"],
        ["뿌리 염색", "60,000"],
        ["열펌", "120,000"],
        ["두피 클리닉", "80,000"],
      ].flatMap(([name, price], i) => [
        text({
          x: 56,
          y: 620 + i * 82,
          w: 200,
          h: 40,
          text: name,
          size: 44,
          weight: 700,
          color: "#4a3a40",
        }),
        text({
          x: 200,
          y: 620 + i * 82,
          w: 160,
          h: 40,
          text: price,
          size: 44,
          weight: 700,
          color: "#8a4f68",
          align: "right",
          font: "gothic-a1",
        }),
      ]),

      rect({ x: 56, y: 1010, w: 300, h: 96, fill: "#8a4f68", radius: 8 }),
      text({
        x: 56,
        y: 1034,
        w: 300,
        h: 48,
        text: "첫 방문 30% 할인",
        size: 44,
        weight: 700,
        color: "#ffffff",
        align: "center",
      }),

      text({
        x: 56,
        y: 1500,
        w: 420,
        h: 100,
        text: "예약 02-546-0000\n강남구 선릉로 21, 2층\n화 – 일 10:00 – 20:00 (월요일 휴무)",
        size: 34,
        color: "#6b5560",
        lineHeight: 1.9,
      }),
    ],
  },

  /* ---------------------------------------------------------
     3. 헬스장 — 도형 하나로 미는 판
     --------------------------------------------------------- */
  {
    id: "sb-fitness-open",
    name: "피트니스 배너",
    note: "굵은 도형 하나와 숫자. 등록 안내에 필요한 것만 남겼습니다.",
    industry: "fitness",
    style: "minimal",
    palette: ["navy", "mono"],
    art: ["sb-fitness-minimal"],
    tags: ["헬스", "등록", "가격"],
    background: { color: "#eceef2" },
    build: ({ w, h, bleed }) => [
      image("sb-fitness-minimal", {
        x: -bleed,
        y: -bleed,
        w: w + bleed * 2,
        h: h + bleed * 2,
        opacity: 0.95,
      }),

      text({
        x: 60,
        y: 140,
        w: w - 120,
        h: 34,
        text: "성산 피트니스 · 24시간",
        size: 44,
        weight: 700,
        color: "#3a3f57",
        letterSpacing: 0.12,
      }),
      text({
        x: 60,
        y: 200,
        w: w - 120,
        h: 190,
        text: "오늘\n시작하세요",
        size: 124,
        weight: 700,
        color: "#1c2340",
        lineHeight: 1.3,
        letterSpacing: -0.03,
        font: "gothic-a1",
      }),

      rect({ x: 60, y: 440, w: w - 120, h: 230, fill: "#ffffff", radius: 10, opacity: 0.92 }),
      text({
        x: 90,
        y: 476,
        w: w - 180,
        h: 36,
        text: "오픈 회원 · 선착순 100명",
        size: 38,
        weight: 700,
        color: "#6b7280",
      }),
      text({
        x: 90,
        y: 530,
        w: w - 180,
        h: 80,
        text: "6개월 39만원",
        size: 96,
        weight: 700,
        color: "#1c2340",
        font: "gothic-a1",
      }),
      text({
        x: 90,
        y: 622,
        w: w - 180,
        h: 34,
        text: "정가 58만원 · GX·필라테스 그룹수업 포함",
        size: 32,
        color: "#6b7280",
      }),

      ...bullets({
        x: 60,
        y: 730,
        w: w - 120,
        size: 40,
        gap: 62,
        color: "#3a3f57",
        lines: [
          "러닝머신 24대 · 프리웨이트존",
          "샤워실 · 수건 무료 · 락커 제공",
          "주차 2시간 무료",
        ],
      }),

      text({
        x: 60,
        y: 1520,
        w: w - 120,
        h: 60,
        text: "02-541-0000",
        size: 76,
        weight: 700,
        color: "#1c2340",
        font: "gothic-a1",
      }),
      text({
        x: 60,
        y: 1600,
        w: w - 120,
        h: 40,
        text: "마포구 성미산로 50, 지하 1층",
        size: 34,
        color: "#6b7280",
      }),
    ],
  },

  /* ---------------------------------------------------------
     4. 병원 — 밝은 사진과 진료 시간표
     --------------------------------------------------------- */
  {
    id: "sb-clinic-hours",
    name: "진료 안내 배너",
    note: "밝은 사진 아래 시간표. 병원 입구에 세우는 것.",
    industry: "clinic",
    style: "photo",
    palette: ["pastel", "green"],
    art: ["sb-clinic-photo"],
    tags: ["병원", "진료시간", "안내"],
    background: { color: "#ffffff" },
    build: ({ w, bleed }) => [
      image("sb-clinic-photo", { x: -bleed, y: -bleed, w: w + bleed * 2, h: 700 + bleed }),

      rect({ x: 0, y: 560, w: 420, h: 140, fill: "#ffffff" }),
      text({
        x: 40,
        y: 592,
        w: 360,
        h: 44,
        text: "성산내과의원",
        size: 58,
        weight: 700,
        color: INK.teal,
        font: "gothic-a1",
      }),
      text({
        x: 40,
        y: 648,
        w: 360,
        h: 30,
        text: "내과 · 소화기 · 건강검진",
        size: 32,
        color: INK.grey,
      }),

      text({
        x: 60,
        y: 780,
        w: w - 120,
        h: 60,
        text: "진료 시간",
        size: 56,
        weight: 700,
        color: INK.black,
        font: "gothic-a1",
      }),
      rule({ x: 60, y: 860, w: w - 120, fill: INK.teal, h: 2 }),

      ...[
        ["월 · 화 · 목 · 금", "09:00 – 18:00"],
        ["수요일", "09:00 – 13:00"],
        ["토요일", "09:00 – 13:00"],
        ["점심시간", "13:00 – 14:00"],
        ["일요일 · 공휴일", "휴진"],
      ].flatMap(([day, time], i) => [
        text({
          x: 60,
          y: 900 + i * 80,
          w: 260,
          h: 40,
          text: day,
          size: 40,
          color: INK.soft,
        }),
        text({
          x: 300,
          y: 900 + i * 80,
          w: 240,
          h: 40,
          text: time,
          size: 42,
          weight: 700,
          color: INK.black,
          align: "right",
          font: "gothic-a1",
        }),
        rule({ x: 60, y: 960 + i * 80, w: w - 120, fill: "#e5e7eb" }),
      ]),

      rect({ x: 60, y: 1340, w: w - 120, h: 120, fill: "#eef7f5", radius: 8 }),
      text({
        x: 60,
        y: 1372,
        w: w - 120,
        h: 56,
        text: "예약 02-337-0000",
        size: 62,
        weight: 700,
        color: INK.teal,
        align: "center",
        font: "gothic-a1",
      }),
      text({
        x: 60,
        y: 1500,
        w: w - 120,
        h: 40,
        text: "마포구 성미산로 30, 2층 · 망원역 2번 출구",
        size: 32,
        color: INK.grey,
        align: "center",
      }),
    ],
  },

  /* ---------------------------------------------------------
     5. 학원 설명회 — 색면과 큰 날짜
     --------------------------------------------------------- */
  {
    id: "sb-academy-brief",
    name: "설명회 안내 배너",
    note: "날짜를 가운데에 크게. 로비에 세워 두는 안내물.",
    industry: "academy",
    style: "minimal",
    palette: ["navy", "warm"],
    tags: ["학원", "설명회", "예약"],
    background: { color: "#fbfaf8" },
    build: ({ w, bleed }) => [
      rect({ x: -bleed, y: -bleed, w: w + bleed * 2, h: 30 + bleed, fill: INK.navy }),

      text({
        x: 60,
        y: 150,
        w: w - 120,
        h: 34,
        text: "2027 대입 학부모 설명회",
        size: 44,
        weight: 700,
        color: "#c2410c",
        letterSpacing: 0.08,
      }),
      text({
        x: 60,
        y: 212,
        w: w - 120,
        h: 250,
        text: "무엇을\n먼저\n정해야 하는가",
        size: 104,
        weight: 700,
        color: INK.navy,
        lineHeight: 1.34,
        letterSpacing: -0.03,
        font: "gothic-a1",
      }),

      rect({ x: 60, y: 620, w: w - 120, h: 300, fill: INK.navy, radius: 12 }),
      text({
        x: 60,
        y: 668,
        w: w - 120,
        h: 40,
        text: "3월 15일 토요일",
        size: 52,
        weight: 700,
        color: "#a9c0e8",
        align: "center",
      }),
      text({
        x: 60,
        y: 740,
        w: w - 120,
        h: 90,
        text: "오전 10시",
        size: 116,
        weight: 700,
        color: "#ffffff",
        align: "center",
        font: "gothic-a1",
      }),
      text({
        x: 60,
        y: 866,
        w: w - 120,
        h: 36,
        text: "학습관 3층 강당 · 선착순 60명",
        size: 34,
        color: "#a9c0e8",
        align: "center",
      }),

      ...bullets({
        x: 60,
        y: 980,
        w: w - 120,
        size: 38,
        gap: 60,
        color: INK.soft,
        lines: [
          "학년별로 지금 정할 것과 미룰 것",
          "작년 합격 사례를 숫자로",
          "로드맵 책자 배부 · 개별 상담 가능",
        ],
      }),

      text({
        x: 60,
        y: 1490,
        w: w - 120,
        h: 60,
        text: "예약 02-338-0000",
        size: 70,
        weight: 700,
        color: INK.navy,
        font: "gothic-a1",
      }),
      text({
        x: 60,
        y: 1570,
        w: w - 120,
        h: 40,
        text: "성산에듀 학습관 · 마포구 성미산로 22",
        size: 32,
        color: INK.grey,
      }),
    ],
  },

  /* ---------------------------------------------------------
     6. 카페 신메뉴 — 사진을 위에, 값은 아래에
     --------------------------------------------------------- */
  {
    id: "sb-cafe-new",
    name: "신메뉴 배너",
    note: "사진을 위에 두고 값을 아래로. 매장 앞에 세우는 것.",
    industry: "cafe",
    style: "photo",
    palette: ["warm", "ink"],
    art: ["flyer-cafe-photo"],
    tags: ["카페", "신메뉴", "가격"],
    background: { color: "#fffdf9" },
    build: ({ w, bleed }) => [
      image("flyer-cafe-photo", { x: -bleed, y: -bleed, w: w + bleed * 2, h: 760 + bleed }),

      text({
        x: 60,
        y: 830,
        w: w - 120,
        h: 34,
        text: "이번 주 새로 나온 것",
        size: 42,
        weight: 700,
        color: "#a15c00",
        letterSpacing: 0.08,
      }),
      text({
        x: 60,
        y: 890,
        w: w - 120,
        h: 180,
        text: "봄 라테\n세 가지",
        size: 116,
        weight: 700,
        color: "#3b2a18",
        lineHeight: 1.3,
        font: "gothic-a1",
      }),

      rule({ x: 60, y: 1130, w: w - 120, fill: "#e8dcc6", h: 1 }),

      ...[
        ["쑥 라테", "국산 쑥가루", "6,000"],
        ["벚꽃 라테", "직접 만든 시럽", "6,500"],
        ["딸기 라테", "논산 딸기", "6,800"],
      ].flatMap(([name, desc, price], i) => [
        text({
          x: 60,
          y: 1170 + i * 100,
          w: 300,
          h: 44,
          text: name,
          size: 50,
          weight: 700,
          color: "#3b2a18",
        }),
        text({
          x: 60,
          y: 1226 + i * 100,
          w: 300,
          h: 30,
          text: desc,
          size: 30,
          color: "#8a6a45",
        }),
        text({
          x: 340,
          y: 1170 + i * 100,
          w: 200,
          h: 44,
          text: price,
          size: 50,
          weight: 700,
          color: "#a15c00",
          align: "right",
          font: "gothic-a1",
        }),
      ]),

      text({
        x: 60,
        y: 1540,
        w: w - 120,
        h: 40,
        text: "카들리 로스터스 · 마포구 성미산로 12 · 02-336-0000",
        size: 30,
        color: "#8a6a45",
      }),
    ],
  },

  /* ---------------------------------------------------------
     7. 행사 안내 — 붉은 바탕에 크게
     --------------------------------------------------------- */
  {
    id: "sb-event-notice",
    name: "행사 안내 배너",
    note: "행사 이름과 날짜만. 입구에서 세 걸음 밖에서 읽힙니다.",
    industry: "event",
    style: "bold",
    palette: ["red", "warm"],
    tags: ["행사", "축제", "안내"],
    background: { color: "#9f1239" },
    build: ({ w, h, bleed }) => [
      ellipse({ x: -120, y: 980, w: 840, h: 840, fill: "#b91c4b", opacity: 0.6 }),
      rect({ x: -bleed, y: h - 40, w: w + bleed * 2, h: 40 + bleed, fill: "#f2c14e" }),

      text({
        x: 56,
        y: 150,
        w: w - 112,
        h: 40,
        text: "제7회",
        size: 52,
        weight: 700,
        color: "#f7c8d2",
        letterSpacing: 0.14,
      }),
      text({
        x: 56,
        y: 216,
        w: w - 112,
        h: 260,
        text: "성산동\n밤마실",
        size: 148,
        weight: 400,
        color: "#ffffff",
        lineHeight: 1.28,
        font: "black-han-sans",
      }),

      rect({ x: 56, y: 560, w: w - 112, h: 170, fill: "#f2c14e", radius: 10 }),
      text({
        x: 56,
        y: 596,
        w: w - 112,
        h: 46,
        text: "10월 4일 토요일",
        size: 56,
        weight: 700,
        color: "#7a1030",
        align: "center",
      }),
      text({
        x: 56,
        y: 660,
        w: w - 112,
        h: 46,
        text: "오후 5시 – 밤 11시",
        size: 52,
        weight: 700,
        color: "#7a1030",
        align: "center",
      }),

      ...bullets({
        x: 56,
        y: 800,
        w: w - 112,
        size: 40,
        gap: 64,
        color: "#ffdde4",
        lines: ["먹거리 스물여덟 집", "마당 무대 · 밤 8시 공연", "문화의거리 일대"],
      }),

      text({
        x: 56,
        y: 1560,
        w: w - 112,
        h: 40,
        text: "주최 성산동 상인회 · 02-330-0000",
        size: 32,
        color: "#f7c8d2",
      }),
    ],
  },

  /* ---------------------------------------------------------
     8. 단체 모집 — 초록과 활자
     --------------------------------------------------------- */
  {
    id: "sb-community-join",
    name: "회원 모집 배너",
    note: "글자와 선만으로. 주민센터·단체 게시에 어울립니다.",
    industry: "community",
    style: "type",
    palette: ["green", "mono"],
    art: ["mark-leaf-minimal"],
    tags: ["단체", "모집", "봉사"],
    background: { color: "#f7f9f5" },
    build: ({ w, bleed }) => [
      rect({ x: -bleed, y: -bleed, w: w + bleed * 2, h: 24 + bleed, fill: INK.green }),
      image("mark-leaf-minimal", {
        x: w / 2 - 130,
        y: 620,
        w: 260,
        h: 260,
        fit: "contain",
        opacity: 0.9,
      }),

      text({
        x: 56,
        y: 170,
        w: w - 112,
        h: 36,
        text: "성산동 마을정원 가꾸기",
        size: 44,
        weight: 700,
        color: INK.green,
        letterSpacing: 0.08,
        align: "center",
      }),
      text({
        x: 56,
        y: 240,
        w: w - 112,
        h: 200,
        text: "같이 심을\n분을 찾습니다",
        size: 104,
        weight: 700,
        color: INK.green,
        align: "center",
        lineHeight: 1.36,
        font: "gothic-a1",
      }),
      text({
        x: 80,
        y: 470,
        w: w - 160,
        h: 100,
        text: "매주 토요일 아침 두 시간,\n동네 화단을 함께 돌봅니다.",
        size: 40,
        color: INK.soft,
        align: "center",
        lineHeight: 1.9,
      }),

      rule({ x: 140, y: 940, w: w - 280, fill: "#c9d6c2", h: 1 }),

      ...[
        ["모이는 때", "매주 토요일 오전 9시"],
        ["모이는 곳", "성산동 문화의거리 화단"],
        ["준비물", "없습니다. 장갑은 드립니다"],
        ["대상", "동네에 사는 누구나"],
      ].flatMap(([label, value], i) => [
        text({
          x: 80,
          y: 990 + i * 92,
          w: 160,
          h: 36,
          text: label,
          size: 34,
          weight: 700,
          color: INK.green,
        }),
        text({
          x: 240,
          y: 988 + i * 92,
          w: w - 320,
          h: 36,
          text: value,
          size: 38,
          color: INK.black,
        }),
      ]),

      text({
        x: 56,
        y: 1500,
        w: w - 112,
        h: 100,
        text: "문의 02-330-0000\n성산동 주민자치회",
        size: 38,
        color: INK.soft,
        align: "center",
        lineHeight: 1.9,
      }),
    ],
  },
];

export const STANDING_BANNER_TEMPLATES = composeAll("standing-banner", DRAFTS);
