/* 초대장 디자인 열여덟 벌.

   한 벌 = 그림 한 점 + 그 그림에서 뽑은 색 + 글꼴 두 벌 + 표지 판짜기.
   색은 지어내지 않고 그림에서 뽑았습니다. 그림과 따로 노는 색을 얹으면
   아무리 예쁜 색이어도 카드가 조잡해집니다.

   행사마다 세 벌씩입니다. 같은 행사 안에서도 그림의 결이 다르도록
   골랐습니다 — 유화 한 벌, 판화 한 벌, 파스텔 한 벌 하는 식으로.       */

import type { Design, OccasionId } from "@/lib/occasion/types";

export const DESIGNS: Design[] = [
  /* ══════════ 생일 ══════════ */
  {
    id: "sunflower",
    name: "해바라기",
    occasion: "birthday",
    art: "sunflower.webp",
    note: "레멘의 목판화. 검은 바탕에 노란 꽃 두 송이가 정면을 봅니다.",
    cover: "foot",
    coverInk: "#FBF3E2",
    paper: "#14110C",
    inside: "#FFFCF3",
    ink: "#241F16",
    inkSoft: "#5B5344",
    accent: "#B58021",
    onAccent: "#FFFCF3",
    veil: "#F7EFDC",
    headFont: "hahmlet",
    bodyFont: "gothic-a1",
  },
  {
    id: "chrysanth",
    name: "국화",
    occasion: "birthday",
    art: "chrysanth.webp",
    note: "르누아르의 국화 다발. 색이 스무 가지쯤 섞여 있어 밝습니다.",
    cover: "window",
    coverInk: "#3A2A2C",
    paper: "#FBF4F1",
    inside: "#FFFBF9",
    ink: "#332326",
    inkSoft: "#69565A",
    accent: "#A2495F",
    onAccent: "#FFFBF9",
    veil: "#F8E9EC",
    headFont: "nanum-myeongjo",
    bodyFont: "gowun-dodum",
  },
  {
    id: "cloud",
    name: "꽃구름",
    occasion: "birthday",
    art: "cloud.webp",
    note: "르동의 파스텔. 배 한 척이 분홍빛 안개 속을 지납니다.",
    cover: "head",
    coverInk: "#FFF6F2",
    paper: "#3A2C2A",
    inside: "#FFFAF7",
    ink: "#2E2422",
    inkSoft: "#655551",
    accent: "#9C6551",
    onAccent: "#FFFAF7",
    veil: "#F6E8E1",
    headFont: "diphylleia",
    bodyFont: "gowun-dodum",
  },

  /* ══════════ 돌잔치 ══════════ */
  {
    id: "bird",
    name: "목련과 문조",
    occasion: "firstbirthday",
    art: "bird.webp",
    note: "호쿠사이의 화조화. 여백이 넓어 이름을 크게 앉힐 수 있습니다.",
    cover: "window",
    coverInk: "#33301F",
    paper: "#F7F2E4",
    inside: "#FFFDF5",
    ink: "#2A2719",
    inkSoft: "#5E5943",
    accent: "#7C7A3E",
    onAccent: "#FFFDF5",
    veil: "#F1EEDC",
    headFont: "gowun-batang",
    bodyFont: "gowun-dodum",
  },
  {
    id: "magnolia",
    name: "목련",
    occasion: "firstbirthday",
    art: "magnolia.webp",
    note: "히드의 목련. 짙은 바탕 위 흰 꽃이라 글자가 또렷합니다.",
    cover: "foot",
    coverInk: "#FBF7EC",
    paper: "#141A18",
    inside: "#FCFBF6",
    ink: "#20241F",
    inkSoft: "#525A4F",
    accent: "#6E7A5C",
    onAccent: "#FCFBF6",
    veil: "#EDF0E6",
    headFont: "nanum-myeongjo",
    bodyFont: "gothic-a1",
  },
  {
    id: "blossom",
    name: "벚꽃 연회",
    occasion: "firstbirthday",
    art: "blossom.webp",
    note: "우타마로의 목판화. 벚꽃 아래 사람들이 모여 있습니다.",
    cover: "center",
    coverInk: "#3B2621",
    paper: "#F6E9DE",
    inside: "#FFFAF5",
    ink: "#33231E",
    inkSoft: "#6B564D",
    accent: "#B0644F",
    onAccent: "#FFFAF5",
    veil: "#F7E7DD",
    headFont: "kirang-haerang",
    bodyFont: "gowun-dodum",
  },

  /* ══════════ 집들이 ══════════ */
  {
    id: "apple",
    name: "사과 바구니",
    occasion: "housewarming",
    art: "apple.webp",
    note: "세잔의 정물. 식탁보와 과일, 집에 사람을 부르는 그림입니다.",
    cover: "window",
    coverInk: "#2F3128",
    paper: "#F4F2E9",
    inside: "#FCFCF6",
    ink: "#262920",
    inkSoft: "#585B4C",
    accent: "#7B7A4E",
    onAccent: "#FCFCF6",
    veil: "#EEEFE2",
    headFont: "gowun-batang",
    bodyFont: "gothic-a1",
  },
  {
    id: "table",
    name: "식탁 한 귀퉁이",
    occasion: "housewarming",
    art: "table.webp",
    note: "팡탱라투르. 흰 식탁보, 유리잔, 그리고 꽃 한 다발.",
    cover: "foot",
    coverInk: "#F8F6EE",
    paper: "#191B18",
    inside: "#FBFBF7",
    ink: "#22241F",
    inkSoft: "#545750",
    accent: "#6B6350",
    onAccent: "#FBFBF7",
    veil: "#EFEDE4",
    headFont: "serif",
    bodyFont: "sans",
  },
  {
    id: "lily",
    name: "수련 연못",
    occasion: "housewarming",
    art: "lily.webp",
    note: "모네의 연못. 초록이 화면을 다 덮어 눈이 편안합니다.",
    cover: "head",
    coverInk: "#F4F7EE",
    paper: "#1E2A20",
    inside: "#FAFCF6",
    ink: "#1F261E",
    inkSoft: "#4F594B",
    accent: "#4E7050",
    onAccent: "#FAFCF6",
    veil: "#E8F0E5",
    headFont: "gowun-batang",
    bodyFont: "gowun-dodum",
  },

  /* ══════════ 개업 ══════════ */
  {
    id: "fruit",
    name: "포도와 레몬",
    occasion: "opening",
    art: "fruit.webp",
    note: "반 고흐의 붓질. 노랑과 보라가 부딪쳐 소리가 납니다.",
    cover: "foot",
    coverInk: "#FDF8EA",
    paper: "#191720",
    inside: "#FFFCF2",
    ink: "#231F17",
    inkSoft: "#575043",
    accent: "#B07C1E",
    onAccent: "#FFFCF2",
    veil: "#F8F0DA",
    headFont: "do-hyeon",
    bodyFont: "gothic-a1",
  },
  {
    id: "maple",
    name: "벚꽃과 단풍",
    occasion: "opening",
    art: "maple.webp",
    note: "도사 미쓰오키의 금병풍. 금박 바탕에 시를 적은 종이가 걸립니다.",
    cover: "window",
    coverInk: "#3A2A18",
    paper: "#F6ECD8",
    inside: "#FFFBF0",
    ink: "#2E2214",
    inkSoft: "#63523B",
    accent: "#9B7326",
    onAccent: "#FFFBF0",
    veil: "#F5EBD6",
    headFont: "hahmlet",
    bodyFont: "gowun-dodum",
  },
  {
    id: "wave",
    name: "큰 파도",
    occasion: "opening",
    art: "wave.webp",
    note: "호쿠사이. 이보다 기세 좋은 그림은 많지 않습니다.",
    cover: "center",
    coverInk: "#F6F3E9",
    paper: "#16283C",
    inside: "#FAFBF7",
    ink: "#1B2430",
    inkSoft: "#4B5563",
    accent: "#20486E",
    onAccent: "#FAFBF7",
    veil: "#E6EDF3",
    headFont: "black-han-sans",
    bodyFont: "gothic-a1",
  },

  /* ══════════ 파티 · 모임 ══════════ */
  {
    id: "poppy",
    name: "양귀비밭",
    occasion: "party",
    art: "poppy.webp",
    note: "모네. 초록 들판에 붉은 점이 흩뿌려진 여름 그림입니다.",
    cover: "head",
    coverInk: "#FBF8F2",
    paper: "#27332C",
    inside: "#FCFCF7",
    ink: "#242A24",
    inkSoft: "#535B51",
    accent: "#9A4034",
    onAccent: "#FCFCF7",
    veil: "#F4E7E2",
    headFont: "jua",
    bodyFont: "gothic-a1",
  },
  {
    id: "beach",
    name: "해변",
    occasion: "party",
    art: "beach.webp",
    note: "모네의 생타드레스. 흐린 하늘과 바다, 배 몇 척.",
    cover: "window",
    coverInk: "#26333A",
    paper: "#EFF2F1",
    inside: "#FAFCFC",
    ink: "#1F2A30",
    inkSoft: "#4E5A61",
    accent: "#3F6B78",
    onAccent: "#FAFCFC",
    veil: "#E4EEF0",
    headFont: "gowun-batang",
    bodyFont: "gowun-dodum",
  },
  {
    id: "iris",
    name: "붓꽃",
    occasion: "party",
    art: "iris.webp",
    note: "모네 말년의 붓꽃. 초록과 보라가 뒤엉킨 큰 화면입니다.",
    cover: "foot",
    coverInk: "#F6F6EE",
    paper: "#1F2A22",
    inside: "#FBFCF7",
    ink: "#232A22",
    inkSoft: "#525A4E",
    accent: "#5B5B8A",
    onAccent: "#FBFCF7",
    veil: "#EAEAF3",
    headFont: "diphylleia",
    bodyFont: "gowun-dodum",
  },

  /* ══════════ 기념일 · 감사 ══════════ */
  {
    id: "bouquet",
    name: "질그릇의 꽃다발",
    occasion: "anniversary",
    art: "bouquet.webp",
    note: "브뤼헐. 검은 배경에 꽃 백여 송이가 촘촘히 박혀 있습니다.",
    cover: "foot",
    coverInk: "#F7EFE4",
    paper: "#100E0C",
    inside: "#FDFAF4",
    ink: "#26201A",
    inkSoft: "#5B5148",
    accent: "#8E5A3C",
    onAccent: "#FDFAF4",
    veil: "#F4E9DD",
    headFont: "nanum-myeongjo",
    bodyFont: "gowun-dodum",
  },
  {
    id: "rose",
    name: "화병의 장미",
    occasion: "anniversary",
    art: "rose.webp",
    note: "쇠라의 목탄 소묘. 색이 없어 오히려 격이 있습니다.",
    cover: "window",
    coverInk: "#2A2724",
    paper: "#F3F0E9",
    inside: "#FBFAF6",
    ink: "#232120",
    inkSoft: "#57534E",
    accent: "#57534E",
    onAccent: "#FBFAF6",
    veil: "#EEECE6",
    headFont: "serif",
    bodyFont: "sans",
  },
  {
    id: "harbor",
    name: "요크 항구",
    occasion: "anniversary",
    art: "harbor.webp",
    note: "히드의 저녁 바다. 해가 물 위로 낮게 걸려 있습니다.",
    cover: "center",
    coverInk: "#FBF4E6",
    paper: "#2A2417",
    inside: "#FDFBF4",
    ink: "#27231A",
    inkSoft: "#5A5346",
    accent: "#96702C",
    onAccent: "#FDFBF4",
    veil: "#F5EEDD",
    headFont: "gowun-batang",
    bodyFont: "gothic-a1",
  },
];

const BY_ID = new Map(DESIGNS.map((d) => [d.id, d]));

/** 없는 id 가 들어와도 화면이 비지 않도록 첫 디자인으로 되돌립니다. */
export const FALLBACK_DESIGN = DESIGNS[0]!;

export function getDesign(id: string | undefined): Design {
  return (id && BY_ID.get(id)) || FALLBACK_DESIGN;
}

export function designsOf(occasion: OccasionId): Design[] {
  return DESIGNS.filter((d) => d.occasion === occasion);
}

/** 디자인의 색을 CSS 변수로 — 카드 안팎이 모두 이 변수만 봅니다. */
export function designVars(d: Design): Record<string, string> {
  return {
    "--oc-paper": d.paper,
    "--oc-cover-ink": d.coverInk,
    "--oc-inside": d.inside,
    "--oc-ink": d.ink,
    "--oc-ink-soft": d.inkSoft,
    "--oc-accent": d.accent,
    "--oc-on-accent": d.onAccent,
    "--oc-veil": d.veil,
  };
}
