/* 초대장 디자인 스물넉 벌 — 행사 여섯 갈래 × 네 벌.

   한 벌 = 표지 판짜기 + 색 여덟 개 + 글꼴 두 벌.

   ── 그림 표지 여덟 벌 ─────────────────────────────────────────
   미술관 오픈액세스(CC0) 소장품을 씁니다. 색은 지어내지 않고 그림에서
   뽑았습니다. 그림과 따로 노는 색을 얹으면 아무리 예쁜 색이어도 카드가
   조잡해집니다.

   ── 활자 표지 열여섯 벌 ───────────────────────────────────────
   그림이 없습니다. 색면·괘선·활자만으로 짭니다. 실제 고급 문구는
   대부분 이쪽이고, 그림이 없어서 오히려 격이 섭니다. 도형을 직접
   그려 얹는 길은 택하지 않았습니다 — 손으로 그린 벡터 도형은 아무리
   다듬어도 클립아트로 읽힙니다.

   그림을 여덟 벌로 묶어 둔 것도 같은 이유입니다. 스물넉 벌이 전부
   명화면 초대장이 아니라 미술관 굿즈로 보입니다.

   ── 글꼴은 다섯 벌만 씁니다 ───────────────────────────────────
   명조 셋(hahmlet · nanum-myeongjo · gowun-batang)과 고딕 둘
   (gothic-a1 · gowun-dodum). 처음에는 벌마다 다른 글꼴을 골라 열세
   벌을 썼는데, 목록 한 페이지에서 한글 웹폰트 서브셋 145개를 물어
   브라우저가 멎었습니다. 한글 글꼴은 유니코드 구간별로 쪼개져 있어
   한 벌이 파일 열 개쯤 됩니다.

   줄이고 나니 디자인도 나아졌습니다. 장식체를 걷어 내고 좋은 명조로
   통일하는 편이 초대장답습니다.                                  */

import type { Design, OccasionId } from "@/lib/occasion/types";

export const DESIGNS: Design[] = [
  /* ══════════════════ 생일 ══════════════════ */
  {
    id: "sunflower",
    name: "해바라기",
    occasion: "birthday",
    note: "레멘의 목판화. 검은 바탕에 노란 꽃 두 송이가 정면을 봅니다.",
    cover: "foot",
    art: "sunflower.webp",
    coverInk: "#FBF3E2",
    paper: "#14110C",
    inside: "#FFFCF3",
    ink: "#241F16",
    inkSoft: "#5B5344",
    accent: "#B58021",
    onAccent: "#FFFCF3",
    veil: "#F7EFDC",
    headFont: "hahmlet",
    bodyFont: "gothic-a1",
  },
  {
    id: "numeral-ink",
    name: "먹과 숫자",
    occasion: "birthday",
    note: "날짜를 표지의 주인공으로 세웠습니다. 다른 말은 다 뺐습니다.",
    cover: "numeral",
    coverInk: "#F3EFE6",
    paper: "#1B2430",
    inside: "#FCFAF4",
    ink: "#22262C",
    inkSoft: "#565C64",
    accent: "#9A6B3F",
    onAccent: "#FCFAF4",
    veil: "#F1E7DA",
    headFont: "hahmlet",
    bodyFont: "gothic-a1",
  },
  {
    id: "band-coral",
    name: "산호 띠",
    occasion: "birthday",
    note: "위아래 굵은 띠 사이에 종이를 남겨 두는, 오래된 초대장 판입니다.",
    cover: "band",
    coverInk: "#6E3327",
    paper: "#FDF7F1",
    inside: "#FFFBF6",
    ink: "#2E2320",
    inkSoft: "#6A5750",
    accent: "#C0563C",
    onAccent: "#FFFBF6",
    veil: "#F8E4DB",
    headFont: "gowun-batang",
    bodyFont: "gowun-dodum",
  },
  {
    id: "rule-cream",
    name: "괘선",
    occasion: "birthday",
    note: "가는 선 두 줄 사이에 영문을 눕히고, 그 아래 제목을 앉혔습니다.",
    cover: "rule",
    coverInk: "#2F2B1E",
    paper: "#F6F2E6",
    inside: "#FDFCF5",
    ink: "#26231A",
    inkSoft: "#5A554A",
    accent: "#8A7B3E",
    onAccent: "#FDFCF5",
    veil: "#F0EBD9",
    headFont: "nanum-myeongjo",
    bodyFont: "gothic-a1",
  },

  /* ══════════════════ 돌잔치 ══════════════════ */
  {
    id: "bird",
    name: "목련과 문조",
    occasion: "firstbirthday",
    note: "호쿠사이의 화조화. 여백이 넓어 이름을 크게 앉힐 수 있습니다.",
    cover: "window",
    art: "bird.webp",
    coverInk: "#33301F",
    paper: "#F7F2E4",
    inside: "#FFFDF5",
    ink: "#2A2719",
    inkSoft: "#5E5943",
    accent: "#7C7A3E",
    onAccent: "#FFFDF5",
    veil: "#F1EEDC",
    headFont: "gowun-batang",
    bodyFont: "gowun-dodum",
  },
  {
    id: "plate-sky",
    name: "하늘색 판",
    occasion: "firstbirthday",
    note: "옅은 하늘색 한 면에 가는 액자선 하나. 아기 이름이 제일 큽니다.",
    cover: "plate",
    coverInk: "#23383F",
    paper: "#DCE7EC",
    inside: "#FBFDFD",
    ink: "#1F2E33",
    inkSoft: "#52646A",
    accent: "#3E6E7C",
    onAccent: "#FBFDFD",
    veil: "#E3EFF2",
    headFont: "gowun-batang",
    bodyFont: "gowun-dodum",
  },
  {
    id: "corner-oat",
    name: "오트밀 모서리",
    occasion: "firstbirthday",
    note: "네 모서리에만 ㄱ자 선을 둡니다. 청첩장의 오래된 관례입니다.",
    cover: "corner",
    coverInk: "#3A3226",
    paper: "#F3EDE1",
    inside: "#FDFBF6",
    ink: "#2C2620",
    inkSoft: "#62594E",
    accent: "#A2794A",
    onAccent: "#FDFBF6",
    veil: "#F2E7D6",
    headFont: "nanum-myeongjo",
    bodyFont: "gothic-a1",
  },
  {
    id: "mono-clay",
    name: "이니셜",
    occasion: "firstbirthday",
    note: "이름 첫 글자를 원 안에 넣습니다. 그림이 없어도 표지가 섭니다.",
    cover: "mono",
    coverInk: "#453A33",
    paper: "#E7DED6",
    inside: "#FCFAF8",
    ink: "#302823",
    inkSoft: "#665B54",
    accent: "#8D6E5D",
    onAccent: "#FCFAF8",
    veil: "#EFE4DC",
    headFont: "nanum-myeongjo",
    bodyFont: "gowun-dodum",
  },

  /* ══════════════════ 집들이 ══════════════════ */
  {
    id: "table",
    name: "식탁 한 귀퉁이",
    occasion: "housewarming",
    note: "팡탱라투르. 흰 식탁보, 유리잔, 그리고 꽃 한 다발.",
    cover: "foot",
    art: "table.webp",
    coverInk: "#F8F6EE",
    paper: "#191B18",
    inside: "#FBFBF7",
    ink: "#22241F",
    inkSoft: "#545750",
    accent: "#6B6350",
    onAccent: "#FBFBF7",
    veil: "#EFEDE4",
    headFont: "nanum-myeongjo",
    bodyFont: "gothic-a1",
  },
  {
    id: "lily",
    name: "수련 연못",
    occasion: "housewarming",
    note: "모네의 연못. 초록이 화면을 다 덮어 눈이 편안합니다.",
    cover: "head",
    art: "lily.webp",
    coverInk: "#F4F7EE",
    paper: "#1E2A20",
    inside: "#FAFCF6",
    ink: "#1F261E",
    inkSoft: "#4F594B",
    accent: "#4E7050",
    onAccent: "#FAFCF6",
    veil: "#E8F0E5",
    headFont: "gowun-batang",
    bodyFont: "gowun-dodum",
  },
  {
    id: "stripe-olive",
    name: "올리브 줄무늬",
    occasion: "housewarming",
    note: "아주 가는 세로줄 위에 흰 라벨을 붙였습니다. 편지지의 문법입니다.",
    cover: "stripe",
    coverInk: "#303426",
    paper: "#EDEDE2",
    inside: "#FCFCF7",
    ink: "#272A20",
    inkSoft: "#575B4D",
    accent: "#64703F",
    onAccent: "#FCFCF7",
    veil: "#EAEEDC",
    headFont: "gowun-batang",
    bodyFont: "gothic-a1",
  },
  {
    id: "stack-sand",
    name: "모래빛 조판",
    occasion: "housewarming",
    note: "제목을 왼쪽에 크게 쌓고 아래에 굵은 선 하나. 요즘 문구의 판입니다.",
    cover: "stack",
    coverInk: "#322D24",
    paper: "#E8E1D4",
    inside: "#FDFBF5",
    ink: "#2A2620",
    inkSoft: "#5D564C",
    accent: "#96662F",
    onAccent: "#FDFBF5",
    veil: "#F1E7D5",
    headFont: "hahmlet",
    bodyFont: "gothic-a1",
  },

  /* ══════════════════ 개업 · 오픈 ══════════════════ */
  {
    id: "wave",
    name: "큰 파도",
    occasion: "opening",
    note: "호쿠사이. 이보다 기세 좋은 그림은 많지 않습니다.",
    cover: "center",
    art: "wave.webp",
    coverInk: "#F6F3E9",
    paper: "#16283C",
    inside: "#FAFBF7",
    ink: "#1B2430",
    inkSoft: "#4B5563",
    accent: "#20486E",
    onAccent: "#FAFBF7",
    veil: "#E6EDF3",
    headFont: "hahmlet",
    bodyFont: "gothic-a1",
  },
  {
    id: "band-ink",
    name: "먹 띠",
    occasion: "opening",
    note: "검정과 흰 종이만. 상호가 길어도 흔들리지 않는 판입니다.",
    cover: "band",
    coverInk: "#1D1F22",
    paper: "#FAF8F3",
    inside: "#FDFCF9",
    ink: "#1F2124",
    inkSoft: "#55585C",
    accent: "#1D1F22",
    onAccent: "#FDFCF9",
    veil: "#E9EAEC",
    headFont: "hahmlet",
    bodyFont: "gothic-a1",
  },
  {
    id: "numeral-gold",
    name: "놋쇠 숫자",
    occasion: "opening",
    note: "어두운 종이에 문 여는 날짜만 크게. 놋쇠 한 색으로 눌렀습니다.",
    cover: "numeral",
    coverInk: "#F0E3C4",
    paper: "#1F1A12",
    inside: "#FFFCF2",
    ink: "#241E14",
    inkSoft: "#58503F",
    accent: "#A9832E",
    onAccent: "#FFFCF2",
    veil: "#F5EDD9",
    headFont: "hahmlet",
    bodyFont: "gothic-a1",
  },
  {
    id: "plate-forest",
    name: "짙은 숲 판",
    occasion: "opening",
    note: "초록 한 면에 가는 액자선. 카페와 공방에 잘 맞습니다.",
    cover: "plate",
    coverInk: "#EDF3EC",
    paper: "#1E3229",
    inside: "#FAFCF8",
    ink: "#1E2A22",
    inkSoft: "#4E5B50",
    accent: "#3F6B4E",
    onAccent: "#FAFCF8",
    veil: "#E6F0E7",
    headFont: "gowun-batang",
    bodyFont: "gothic-a1",
  },

  /* ══════════════════ 파티 · 모임 ══════════════════ */
  {
    id: "blossom",
    name: "벚꽃 연회",
    occasion: "party",
    note: "우타마로의 목판화. 벚꽃 아래 사람들이 모여 있습니다.",
    cover: "center",
    art: "blossom.webp",
    coverInk: "#3B2621",
    paper: "#F6E9DE",
    inside: "#FFFAF5",
    ink: "#33231E",
    inkSoft: "#6B564D",
    accent: "#B0644F",
    onAccent: "#FFFAF5",
    veil: "#F7E7DD",
    headFont: "nanum-myeongjo",
    bodyFont: "gowun-dodum",
  },
  {
    id: "stack-night",
    name: "밤",
    occasion: "party",
    note: "남색 한 면에 제목을 왼쪽으로 몰아 쌓았습니다. 저녁 모임의 색입니다.",
    cover: "stack",
    coverInk: "#EDEBF5",
    paper: "#191C2B",
    inside: "#FBFAFD",
    ink: "#22242F",
    inkSoft: "#565A67",
    accent: "#5B5B8A",
    onAccent: "#FBFAFD",
    veil: "#E9E9F4",
    headFont: "hahmlet",
    bodyFont: "gothic-a1",
  },
  {
    id: "stripe-plum",
    name: "자두 줄무늬",
    occasion: "party",
    note: "가는 줄무늬에 라벨 하나. 격식은 덜고 분위기만 남겼습니다.",
    cover: "stripe",
    coverInk: "#40222F",
    paper: "#F3E9EE",
    inside: "#FDFAFB",
    ink: "#33222B",
    inkSoft: "#6A555F",
    accent: "#8A3E5B",
    onAccent: "#FDFAFB",
    veil: "#F6E4EC",
    headFont: "gowun-batang",
    bodyFont: "gowun-dodum",
  },
  {
    id: "mono-coral",
    name: "산호 이니셜",
    occasion: "party",
    note: "모임 이름의 첫 글자를 원 안에. 동아리와 송년회에 맞습니다.",
    cover: "mono",
    coverInk: "#5B2E22",
    paper: "#F7EDE6",
    inside: "#FFFAF6",
    ink: "#33241E",
    inkSoft: "#6B564C",
    accent: "#C05A34",
    onAccent: "#FFFAF6",
    veil: "#FAE5D9",
    headFont: "hahmlet",
    bodyFont: "gothic-a1",
  },

  /* ══════════════════ 기념일 · 감사 ══════════════════ */
  {
    id: "rose",
    name: "화병의 장미",
    occasion: "anniversary",
    note: "쇠라의 목탄 소묘. 색이 없어 오히려 격이 있습니다.",
    cover: "window",
    art: "rose.webp",
    coverInk: "#2A2724",
    paper: "#F3F0E9",
    inside: "#FBFAF6",
    ink: "#232120",
    inkSoft: "#57534E",
    accent: "#57534E",
    onAccent: "#FBFAF6",
    veil: "#EEECE6",
    headFont: "nanum-myeongjo",
    bodyFont: "gothic-a1",
  },
  {
    id: "iris",
    name: "붓꽃",
    occasion: "anniversary",
    note: "모네 말년의 붓꽃. 초록과 보라가 뒤엉킨 큰 화면입니다.",
    cover: "foot",
    art: "iris.webp",
    coverInk: "#F6F6EE",
    paper: "#1F2A22",
    inside: "#FBFCF7",
    ink: "#232A22",
    inkSoft: "#525A4E",
    accent: "#5B5B8A",
    onAccent: "#FBFCF7",
    veil: "#EAEAF3",
    headFont: "gowun-batang",
    bodyFont: "gowun-dodum",
  },
  {
    id: "rule-ash",
    name: "잿빛 괘선",
    occasion: "anniversary",
    note: "가장 조용한 판입니다. 회갑과 은퇴처럼 말을 아껴야 할 자리에.",
    cover: "rule",
    coverInk: "#2B2A28",
    paper: "#F1F0EC",
    inside: "#FBFBF9",
    ink: "#232120",
    inkSoft: "#57534E",
    accent: "#57534E",
    onAccent: "#FBFBF9",
    veil: "#EAE9E5",
    headFont: "nanum-myeongjo",
    bodyFont: "gothic-a1",
  },
  {
    id: "corner-pearl",
    name: "진주빛 모서리",
    occasion: "anniversary",
    note: "따뜻한 흰 종이에 모서리 선만. 결혼기념일에 가장 많이 고르는 판입니다.",
    cover: "corner",
    coverInk: "#3A3129",
    paper: "#F6F1EA",
    inside: "#FDFBF7",
    ink: "#2C2620",
    inkSoft: "#635A50",
    accent: "#9C7B62",
    onAccent: "#FDFBF7",
    veil: "#F2E7DC",
    headFont: "nanum-myeongjo",
    bodyFont: "gowun-dodum",
  },
];

const BY_ID = new Map(DESIGNS.map((d) => [d.id, d]));

/** 없는 id 가 들어와도 화면이 비지 않도록 첫 디자인으로 되돌립니다. */
export const FALLBACK_DESIGN = DESIGNS[0]!;

export function getDesign(id: string | undefined): Design {
  return (id && BY_ID.get(id)) || FALLBACK_DESIGN;
}

export function designsOf(occasion: OccasionId): Design[] {
  return DESIGNS.filter((d) => d.occasion === occasion);
}

/** 디자인의 색을 CSS 변수로 — 카드 안팎이 모두 이 변수만 봅니다. */
export function designVars(d: Design): Record<string, string> {
  return {
    "--oc-paper": d.paper,
    "--oc-cover-ink": d.coverInk,
    "--oc-inside": d.inside,
    "--oc-ink": d.ink,
    "--oc-ink-soft": d.inkSoft,
    "--oc-accent": d.accent,
    "--oc-on-accent": d.onAccent,
    "--oc-veil": d.veil,
  };
}
