/* ============================================================
   초대장 전용 템플릿

   청첩장 템플릿을 행사용으로 돌려 쓰던 것을 걷어냈습니다. 청첩장
   템플릿은 전부 웨딩 사진 위에 신랑·신부 이름을 얹는 구조라, 생일이나
   집들이에 붙이면 커버에 남의 결혼사진이 깔립니다. 문구만 바꾼다고
   해결되는 문제가 아니었습니다.

   그래서 초대장은 처음부터 다시 만듭니다.
     · 사진이 없어도 커버가 완성됩니다 — 그래픽과 조판만으로 섭니다.
     · 행사마다 성향이 다릅니다. 파티는 밤과 네온이고, 돌잔치는
       파스텔이며, 퇴임식은 담백한 격식입니다. 같은 템플릿을
       열 가지 행사에 돌려 쓰지 않고 행사마다 네 종씩 짭니다.
     · 자료 구조는 청첩장과 같은 Template 을 씁니다. 렌더러·에디터·
       발행이 이미 그 모양을 알고 있어서, 커버 레이아웃만 새로 그리면
       나머지가 전부 따라옵니다.
   ============================================================ */

import type { Template } from "@/lib/invitation";
import type { OccasionKind } from "@/lib/occasion";

export interface OccasionTemplate extends Template {
  /** 이 템플릿이 어느 행사를 위한 것인지 */
  occasion: OccasionKind;
  /** 커버에 얹는 상단 라벨 — 행사 기본값보다 우선합니다 */
  eyebrow: string;
}

/**
 * 초대장 커버 레이아웃.
 *
 * 열두 가지 모두 사진 없이 성립합니다. 편집기의 커버 고르기에서는
 * 초대장일 때 이 목록만 보여 줍니다.
 */
export const OCCASION_COVER_LAYOUTS: {
  id: OccasionTemplate["coverLayout"];
  label: string;
}[] = [
  { id: "confetti", label: "컨페티" },
  { id: "balloon", label: "풍선" },
  { id: "bigdate", label: "빅데이트" },
  { id: "ticket", label: "입장권" },
  { id: "marquee", label: "네온 간판" },
  { id: "lineup", label: "라인업" },
  { id: "sticker", label: "스티커" },
  { id: "house", label: "창가" },
  { id: "tag", label: "꼬리표" },
  { id: "notice", label: "게시문" },
  { id: "stamp", label: "우표" },
  { id: "ribbon", label: "리본" },
];

/* photoSeed 는 초대장에서 쓰이지 않습니다(사진 슬롯이 없습니다).
   Template 이 요구하는 값이라 0 으로 채웁니다. */
const NO_PHOTO = { photoTone: "none", photoSeed: 0 } as const;

export const OCCASION_TEMPLATES: OccasionTemplate[] = [
  /* ══════════ 생일 — 밝고 장난기 있게 ══════════ */
  {
    id: "bd-confetti",
    occasion: "birthday",
    name: "컨페티",
    categories: ["modern"],
    badge: "BEST",
    coverLayout: "confetti",
    headingFont: "sans",
    script: "Happy Birthday",
    eyebrow: "BIRTHDAY PARTY",
    theme: { bg: "#FFF4E6", ink: "#2B211A", sub: "#F7E3C8", accent: "#F1512F", accentSoft: "#FCE0D4" },
    ...NO_PHOTO,
  },
  {
    id: "bd-balloon",
    occasion: "birthday",
    name: "벌룬",
    categories: ["modern"],
    coverLayout: "balloon",
    headingFont: "sans",
    script: "It's My Day",
    eyebrow: "COME CELEBRATE",
    theme: { bg: "#EAF3FF", ink: "#182338", sub: "#D3E4FA", accent: "#2C63D6", accentSoft: "#DCE9FC" },
    ...NO_PHOTO,
  },
  {
    id: "bd-midnight",
    occasion: "birthday",
    name: "미드나잇",
    categories: ["modern"],
    badge: "NEW",
    coverLayout: "bigdate",
    headingFont: "serif",
    script: "Another Year",
    eyebrow: "BIRTHDAY",
    theme: { bg: "#171512", ink: "#F6F1E6", sub: "#241F19", accent: "#F0C24B", accentSoft: "#2E2820" },
    ...NO_PHOTO,
  },
  {
    id: "bd-sticker",
    occasion: "birthday",
    name: "스티커북",
    categories: ["modern"],
    coverLayout: "sticker",
    headingFont: "sans",
    script: "Yay!",
    eyebrow: "BIRTHDAY PARTY",
    theme: { bg: "#FDEBF1", ink: "#2E1B24", sub: "#F8D6E2", accent: "#DE3072", accentSoft: "#FAD9E5" },
    ...NO_PHOTO,
  },

  /* ══════════ 파티 — 밤, 네온, 음악 ══════════ */
  {
    id: "pt-neon",
    occasion: "party",
    name: "네온사인",
    categories: ["modern"],
    badge: "BEST",
    coverLayout: "marquee",
    headingFont: "sans",
    script: "Let's Celebrate",
    eyebrow: "YOU ARE INVITED",
    theme: { bg: "#0B0B15", ink: "#F2EDFF", sub: "#16162A", accent: "#FF3D8A", accentSoft: "#231733" },
    ...NO_PHOTO,
  },
  {
    id: "pt-ticket",
    occasion: "party",
    name: "애드미션",
    categories: ["modern"],
    coverLayout: "ticket",
    headingFont: "sans",
    script: "Admit One",
    eyebrow: "PARTY PASS",
    theme: { bg: "#12151C", ink: "#EAF6F0", sub: "#1B212B", accent: "#4FE0A5", accentSoft: "#1F2E2A" },
    ...NO_PHOTO,
  },
  {
    id: "pt-disco",
    occasion: "party",
    name: "미러볼",
    categories: ["modern"],
    badge: "NEW",
    coverLayout: "lineup",
    headingFont: "sans",
    script: "After Hours",
    eyebrow: "HOUSE PARTY",
    theme: { bg: "#1A0E2E", ink: "#F1E9FF", sub: "#251540", accent: "#C6A2FF", accentSoft: "#2E1B4D" },
    ...NO_PHOTO,
  },
  {
    id: "pt-lounge",
    occasion: "party",
    name: "라운지",
    categories: ["classic"],
    coverLayout: "bigdate",
    headingFont: "serif",
    script: "Come Over",
    eyebrow: "AN EVENING WITH US",
    theme: { bg: "#20180F", ink: "#F3E9DA", sub: "#2C2218", accent: "#D9A441", accentSoft: "#33281B" },
    ...NO_PHOTO,
  },

  /* ══════════ 집들이 — 따뜻한 나무와 창 ══════════ */
  {
    id: "hw-window",
    occasion: "housewarming",
    name: "창가",
    categories: ["minimal"],
    badge: "BEST",
    coverLayout: "house",
    headingFont: "serif",
    script: "Our New Home",
    eyebrow: "HOUSEWARMING",
    theme: { bg: "#F7F2E8", ink: "#2C2519", sub: "#E9DFCC", accent: "#8A6540", accentSoft: "#EFE6D6" },
    ...NO_PHOTO,
  },
  {
    id: "hw-doorplate",
    occasion: "housewarming",
    name: "문패",
    categories: ["minimal"],
    coverLayout: "tag",
    headingFont: "serif",
    script: "Welcome",
    eyebrow: "COME AND SEE",
    theme: { bg: "#EEF0E7", ink: "#232A20", sub: "#DFE3D5", accent: "#5C6B4A", accentSoft: "#E5E9DC" },
    ...NO_PHOTO,
  },
  {
    id: "hw-note",
    occasion: "housewarming",
    name: "손편지",
    categories: ["classic"],
    coverLayout: "notice",
    headingFont: "serif",
    script: "A Little Note",
    eyebrow: "HOUSEWARMING",
    theme: { bg: "#FCF8F0", ink: "#2E241B", sub: "#EFE5D4", accent: "#A65E36", accentSoft: "#F6EADC" },
    ...NO_PHOTO,
  },
  {
    id: "hw-terracotta",
    occasion: "housewarming",
    name: "테라코타",
    categories: ["modern"],
    badge: "NEW",
    coverLayout: "bigdate",
    headingFont: "sans",
    script: "New Place",
    eyebrow: "WE MOVED IN",
    theme: { bg: "#B35A3C", ink: "#FDF3EA", sub: "#9C4B31", accent: "#F6DFC4", accentSoft: "#A25134" },
    ...NO_PHOTO,
  },

  /* ══════════ 돌잔치 — 파스텔, 부드럽게 ══════════ */
  {
    id: "fb-cloud",
    occasion: "firstbirthday",
    name: "구름",
    categories: ["minimal"],
    badge: "BEST",
    coverLayout: "balloon",
    headingFont: "serif",
    script: "First Birthday",
    eyebrow: "OUR FIRST YEAR",
    theme: { bg: "#EFF6FB", ink: "#22303A", sub: "#DCEAF3", accent: "#6FA0C4", accentSoft: "#E2EEF6" },
    ...NO_PHOTO,
  },
  {
    id: "fb-apricot",
    occasion: "firstbirthday",
    name: "살구",
    categories: ["minimal"],
    coverLayout: "sticker",
    headingFont: "sans",
    script: "One!",
    eyebrow: "FIRST BIRTHDAY",
    theme: { bg: "#FFF4EC", ink: "#33261D", sub: "#F8E2D2", accent: "#E39264", accentSoft: "#FBE7D9" },
    ...NO_PHOTO,
  },
  {
    id: "fb-ribbon",
    occasion: "firstbirthday",
    name: "리본",
    categories: ["classic"],
    coverLayout: "ribbon",
    headingFont: "serif",
    script: "One Year Old",
    eyebrow: "FIRST BIRTHDAY",
    theme: { bg: "#F8F2FA", ink: "#2B2331", sub: "#EBDFF0", accent: "#A187C2", accentSoft: "#EEE4F3" },
    ...NO_PHOTO,
  },
  {
    id: "fb-meadow",
    occasion: "firstbirthday",
    name: "새싹",
    categories: ["minimal"],
    badge: "NEW",
    coverLayout: "bigdate",
    headingFont: "serif",
    script: "Turning One",
    eyebrow: "THANK YOU FOR BEING HERE",
    theme: { bg: "#F1F6EE", ink: "#25301F", sub: "#E0EAD9", accent: "#71956A", accentSoft: "#E6EFE1" },
    ...NO_PHOTO,
  },

  /* ══════════ 개업 · 오픈 — 격식과 금빛 ══════════ */
  {
    id: "op-ribbon",
    occasion: "opening",
    name: "테이프커팅",
    categories: ["classic"],
    badge: "BEST",
    coverLayout: "ribbon",
    headingFont: "serif",
    script: "Grand Opening",
    eyebrow: "GRAND OPENING",
    theme: { bg: "#FFFCF4", ink: "#2A2317", sub: "#F0E7D2", accent: "#B18337", accentSoft: "#F7EEDC" },
    ...NO_PHOTO,
  },
  {
    id: "op-signboard",
    occasion: "opening",
    name: "간판",
    categories: ["modern"],
    coverLayout: "marquee",
    headingFont: "sans",
    script: "Now Open",
    eyebrow: "WE ARE OPEN",
    theme: { bg: "#11241D", ink: "#F2EFE4", sub: "#1B322A", accent: "#C9A227", accentSoft: "#20392F" },
    ...NO_PHOTO,
  },
  {
    id: "op-seal",
    occasion: "opening",
    name: "개업인사",
    categories: ["classic"],
    coverLayout: "stamp",
    headingFont: "serif",
    script: "With Thanks",
    eyebrow: "OPENING NOTICE",
    theme: { bg: "#F8F5ED", ink: "#2B241C", sub: "#EBE3D2", accent: "#8E3230", accentSoft: "#F1E7DC" },
    ...NO_PHOTO,
  },
  {
    id: "op-slate",
    occasion: "opening",
    name: "슬레이트",
    categories: ["modern"],
    badge: "NEW",
    coverLayout: "bigdate",
    headingFont: "sans",
    script: "Doors Open",
    eyebrow: "OPENING DAY",
    theme: { bg: "#1E2830", ink: "#EEF3F7", sub: "#28353F", accent: "#E2A85C", accentSoft: "#2C3B46" },
    ...NO_PHOTO,
  },

  /* ══════════ 페스티벌 — 세게, 크게 ══════════ */
  {
    id: "fs-lineup",
    occasion: "festival",
    name: "라인업",
    categories: ["modern"],
    badge: "BEST",
    coverLayout: "lineup",
    headingFont: "sans",
    script: "See You There",
    eyebrow: "FESTIVAL",
    theme: { bg: "#0F1317", ink: "#FFFFFF", sub: "#1A2027", accent: "#E9FF4F", accentSoft: "#232B33" },
    ...NO_PHOTO,
  },
  {
    id: "fs-wristband",
    occasion: "festival",
    name: "손목밴드",
    categories: ["modern"],
    coverLayout: "ticket",
    headingFont: "sans",
    script: "Day Pass",
    eyebrow: "ENTRY PASS",
    theme: { bg: "#E8502A", ink: "#FFF6EC", sub: "#D2451F", accent: "#FFE05C", accentSoft: "#D64B26" },
    ...NO_PHOTO,
  },
  {
    id: "fs-riverside",
    occasion: "festival",
    name: "리버사이드",
    categories: ["modern"],
    badge: "NEW",
    coverLayout: "marquee",
    headingFont: "sans",
    script: "Summer Nights",
    eyebrow: "OPEN AIR",
    theme: { bg: "#061620", ink: "#E6FBF5", sub: "#0C2430", accent: "#37E3B8", accentSoft: "#0F2E3A" },
    ...NO_PHOTO,
  },
  {
    id: "fs-poster",
    occasion: "festival",
    name: "포스터",
    categories: ["modern"],
    coverLayout: "confetti",
    headingFont: "sans",
    script: "Come Join Us",
    eyebrow: "FESTIVAL",
    theme: { bg: "#FBF3D5", ink: "#20180F", sub: "#F0E4B8", accent: "#D63A31", accentSoft: "#F6EBC9" },
    ...NO_PHOTO,
  },

  /* ══════════ 모임 · 동창회 — 차분하게 ══════════ */
  {
    id: "gt-notice",
    occasion: "gathering",
    name: "알림글",
    categories: ["classic"],
    badge: "BEST",
    coverLayout: "notice",
    headingFont: "serif",
    script: "Long Time No See",
    eyebrow: "GET TOGETHER",
    theme: { bg: "#FAF8F2", ink: "#232A33", sub: "#E9E5DA", accent: "#3E5064", accentSoft: "#EDEBE2" },
    ...NO_PHOTO,
  },
  {
    id: "gt-postmark",
    occasion: "gathering",
    name: "소인",
    categories: ["classic"],
    coverLayout: "stamp",
    headingFont: "serif",
    script: "Save the Evening",
    eyebrow: "REUNION",
    theme: { bg: "#F4F1E8", ink: "#2A241B", sub: "#E6E0D0", accent: "#5F4A31", accentSoft: "#EDE8DB" },
    ...NO_PHOTO,
  },
  {
    id: "gt-navy",
    occasion: "gathering",
    name: "네이비",
    categories: ["modern"],
    coverLayout: "bigdate",
    headingFont: "sans",
    script: "We Meet Again",
    eyebrow: "REGULAR MEETING",
    theme: { bg: "#28323E", ink: "#EDF2F7", sub: "#33404F", accent: "#9DB8CE", accentSoft: "#36434F" },
    ...NO_PHOTO,
  },
  {
    id: "gt-cardtag",
    occasion: "gathering",
    name: "이름표",
    categories: ["minimal"],
    badge: "NEW",
    coverLayout: "tag",
    headingFont: "sans",
    script: "Hello Again",
    eyebrow: "GET TOGETHER",
    theme: { bg: "#F0EDE4", ink: "#2A2620", sub: "#E1DCCE", accent: "#7C6A4E", accentSoft: "#E8E4D8" },
    ...NO_PHOTO,
  },

  /* ══════════ 기념일 — 조용하고 우아하게 ══════════ */
  {
    id: "an-gilt",
    occasion: "anniversary",
    name: "금박",
    categories: ["classic"],
    badge: "BEST",
    coverLayout: "ribbon",
    headingFont: "serif",
    script: "Anniversary",
    eyebrow: "A QUIET CELEBRATION",
    theme: { bg: "#FCF8F4", ink: "#2C241E", sub: "#EDE2D6", accent: "#B08650", accentSoft: "#F4EBE0" },
    ...NO_PHOTO,
  },
  {
    id: "an-velvet",
    occasion: "anniversary",
    name: "벨벳",
    categories: ["classic"],
    coverLayout: "bigdate",
    headingFont: "serif",
    script: "Ten Years",
    eyebrow: "ANNIVERSARY",
    theme: { bg: "#251C22", ink: "#F5EDE5", sub: "#31252C", accent: "#D6B183", accentSoft: "#372932" },
    ...NO_PHOTO,
  },
  {
    id: "an-letter",
    occasion: "anniversary",
    name: "편지",
    categories: ["classic"],
    coverLayout: "stamp",
    headingFont: "serif",
    script: "To You",
    eyebrow: "WITH GRATITUDE",
    theme: { bg: "#F8F1F1", ink: "#31232A", sub: "#EBDDDE", accent: "#9C5B63", accentSoft: "#F1E3E4" },
    ...NO_PHOTO,
  },
  {
    id: "an-olive",
    occasion: "anniversary",
    name: "올리브",
    categories: ["minimal"],
    badge: "NEW",
    coverLayout: "tag",
    headingFont: "serif",
    script: "Still Here",
    eyebrow: "ANNIVERSARY",
    theme: { bg: "#F0EFE8", ink: "#262B23", sub: "#E1E1D5", accent: "#6C7A62", accentSoft: "#E8E8DE" },
    ...NO_PHOTO,
  },

  /* ══════════ 졸업 · 수료 — 격식 있는 잉크 ══════════ */
  {
    id: "gd-diploma",
    occasion: "graduation",
    name: "학위기",
    categories: ["classic"],
    badge: "BEST",
    coverLayout: "notice",
    headingFont: "serif",
    script: "We Did It",
    eyebrow: "GRADUATION",
    theme: { bg: "#F9F8F4", ink: "#1E2A3C", sub: "#E7E6DE", accent: "#22456E", accentSoft: "#EAEBE4" },
    ...NO_PHOTO,
  },
  {
    id: "gd-seal",
    occasion: "graduation",
    name: "인장",
    categories: ["classic"],
    coverLayout: "stamp",
    headingFont: "serif",
    script: "Commencement",
    eyebrow: "GRADUATION",
    theme: { bg: "#F3F3EE", ink: "#22301F", sub: "#E4E5DA", accent: "#2F5040", accentSoft: "#E9EAE1" },
    ...NO_PHOTO,
  },
  {
    id: "gd-navygold",
    occasion: "graduation",
    name: "네이비골드",
    categories: ["modern"],
    coverLayout: "bigdate",
    headingFont: "serif",
    script: "The Last Day",
    eyebrow: "CLASS OF 2026",
    theme: { bg: "#152740", ink: "#EFF3F8", sub: "#1E3450", accent: "#D6B15C", accentSoft: "#223A57" },
    ...NO_PHOTO,
  },
  {
    id: "gd-laurel",
    occasion: "graduation",
    name: "월계관",
    categories: ["classic"],
    badge: "NEW",
    coverLayout: "ribbon",
    headingFont: "serif",
    script: "Congratulations",
    eyebrow: "GRADUATION",
    theme: { bg: "#FDFAF4", ink: "#2E1D22", sub: "#EFE4DA", accent: "#7E2E3C", accentSoft: "#F5EAE2" },
    ...NO_PHOTO,
  },

  /* ══════════ 퇴임 · 송별 — 담백한 예의 ══════════ */
  {
    id: "rt-farewell",
    occasion: "retirement",
    name: "인사말",
    categories: ["classic"],
    badge: "BEST",
    coverLayout: "notice",
    headingFont: "serif",
    script: "Thank You",
    eyebrow: "FAREWELL",
    theme: { bg: "#FAF9F5", ink: "#2A312C", sub: "#E9E9E1", accent: "#48564E", accentSoft: "#EDEDE5" },
    ...NO_PHOTO,
  },
  {
    id: "rt-nameplate",
    occasion: "retirement",
    name: "명패",
    categories: ["minimal"],
    coverLayout: "tag",
    headingFont: "serif",
    script: "A Long Road",
    eyebrow: "WITH GRATITUDE",
    theme: { bg: "#F2F0EA", ink: "#2B261F", sub: "#E3DFD4", accent: "#6E5D48", accentSoft: "#EAE7DD" },
    ...NO_PHOTO,
  },
  {
    id: "rt-lastmail",
    occasion: "retirement",
    name: "마지막 편지",
    categories: ["classic"],
    coverLayout: "stamp",
    headingFont: "serif",
    script: "One Last Note",
    eyebrow: "FAREWELL",
    theme: { bg: "#F6F5F1", ink: "#243039", sub: "#E6E7E1", accent: "#3F566B", accentSoft: "#EBECE6" },
    ...NO_PHOTO,
  },
  {
    id: "rt-dusk",
    occasion: "retirement",
    name: "해질녘",
    categories: ["modern"],
    badge: "NEW",
    coverLayout: "bigdate",
    headingFont: "serif",
    script: "Well Done",
    eyebrow: "RETIREMENT",
    theme: { bg: "#2C2C28", ink: "#F1F0E9", sub: "#38382F", accent: "#C6AE85", accentSoft: "#3C3C33" },
    ...NO_PHOTO,
  },
];

/** 한 행사에 딸린 템플릿들 */
export function templatesFor(occasion: OccasionKind): OccasionTemplate[] {
  return OCCASION_TEMPLATES.filter((t) => t.occasion === occasion);
}

export function getOccasionTemplate(id: string): OccasionTemplate | undefined {
  return OCCASION_TEMPLATES.find((t) => t.id === id);
}
